CREATE OR REPLACE VIEW RPT_RVA7647.FACULTY_IDS AS

SELECT
CASE WHEN I2.ID_NUMBER IS NOT NULL THEN I2.ID_NUMBER ELSE I.ID_NUMBER END AS "ID_NUMBER",
F.*
FROM FSM_FASIS_LIST F
LEFT OUTER JOIN IDS_BASE I ON F."netid" = I.OTHER_ID AND I.IDS_TYPE_CODE = 'NET'
LEFT OUTER JOIN IDS_BASE I2 ON F."emplid" = I2.OTHER_ID AND I2.IDS_TYPE_CODE = 'FAS' AND I.ID_NUMBER IS NULL
;
