SELECT
------ CONSTITUENT FIELDS
E.ID_NUMBER AS "ID Number",
E.PRIMARY_RECORD_TYPE_DESC AS "Record Type Descr",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
--CASE WHEN E.BIRTH_DT <> '00000000' THEN TRUNC((SYSDATE - TO_DATE(E.BIRTH_DT, 'YYYY-MM-DD'))/ 365.25) ELSE 0 END AS "Age",
E.INSTITUTIONAL_SUFFIX AS "Institutional Suffix",
E.SALUTATION AS "Salutation",
E.LAST_NAME AS "Last Name",
E.FIRST_NAME AS "First Name",
EM.EMPLOYER_NAME AS "Employer Name",
EM.JOB_TITLE AS "Job Title",
E.GENDER_CODE AS "Gender",
E.PREF_CLASS_YEAR AS "Preferred Class Year",
E.PREF_SCHOOL_CODE AS "Preferred School Code",
E.PREF_SCHOOL_NAME AS "Preferred School Name",
E.RECORD_STATUS_CODE AS "Record Status Code",
E.RECORD_STATUS_DESC AS "Record Status Descr",
CASE WHEN E.DEATH_DT <> '00000000' THEN 'Y' ELSE 'N' END AS "Deceased",
E.ADDRESS_STREET1 AS "Address Line 1",
E.ADDRESS_STREET2 AS "Address Line 2",
E.CITY AS "City",
E.STATE_CODE AS "ST",
SUBSTR(E.ZIPCODE,1,5) AS "ZIP",
E.COUNTRY_NAME AS "Country",
EMAIL_ADDRESS AS "Email",
CASE WHEN LENGTH(PHONE_AREA_CODE) = 3 AND LENGTH(PHONE_NUMBER) = 7 THEN '(' || E.PHONE_AREA_CODE || ') ' || SUBSTR(E.PHONE_NUMBER,1,3) || '-' || SUBSTR(E.PHONE_NUMBER,4,4) ELSE E.PHONE_NUMBER END AS "Phone",
PR.PROSPECT_MANAGER_NAME AS "Prospect Manager",
--PR.PROSPECT_TEAM_DESC AS "Prospect Team",
FDS.LIFETIME_GIFT_CREDIT_AMOUNT AS "Lifetime Giving",
FDSF.LIFETIME_GIFT_CREDIT_AMOUNT AS "FSM Lifetime Giving",
PR.RATING_DESC AS "Wealth Rating",
E.MAJOR_GIFT_PR_TIER AS "Major Gift Tier",
E.AFFINITY_SCORE AS "Affinity Score",
SHS.DO_NOT_SOLICIT_FLAG AS "Do Not Solicit",
SHS.DO_NOT_MAIL_FLAG AS "Do Not Mail",
SHS.DO_NOT_EMAIL_FLAG AS "Do Not Email"

FROM DM_ARD.DIM_EMPLOYMENT@catrackstobi EM
INNER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON EM.ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y' AND EM.CURRENT_INDICATOR = 'Y' AND EM.DELETED_FLAG = 'N'
INNER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDSF ON E.ID_NUMBER = FDSF.ENTITY_KEY AND FDSF.ANNUAL_FUND_FLAG = 'N' AND FDSF.REPORTING_AREA = 'FS' AND FDSF.FISCAL_YEAR = '2024'
LEFT OUTER JOIN DM_ARD.DIM_SPECIAL_HANDLING_SUMMARY@catrackstobi SHS ON E.ID_NUMBER = SHS.ID_NUMBER
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDS ON E.ID_NUMBER = FDS.ENTITY_KEY AND FDS.ANNUAL_FUND_FLAG = 'N' AND FDS.REPORTING_AREA = 'NA' AND FDS.FISCAL_YEAR = '2024'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT_ENTITY@catrackstobi PE ON E.ID_NUMBER = PE.ID_NUMBER AND PE.CURRENT_INDICATOR = 'Y' AND PE.PROSPECT_ACTIVE_IND = 'Y' AND PE.DELETED_FLAG = 'N'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT@catrackstobi PR ON PE.PROSPECT_ID = PR.PROSPECT_ID AND PR.CURRENT_INDICATOR = 'Y'
WHERE (
EMPLOYER_NAME LIKE '%McDonalds%'
OR EMPLOYER_NAME LIKE '%ConAgra Brands%'
OR EMPLOYER_NAME LIKE '%Kraft Heinz%'
OR EMPLOYER_NAME LIKE '%Mead Johnson Nutrition%'
OR EMPLOYER_NAME LIKE '%Tock%'
OR EMPLOYER_NAME LIKE '%GrubHub%'
OR EMPLOYER_NAME LIKE '%Home Chef%'
OR EMPLOYER_NAME LIKE '%Double Good%'
OR EMPLOYER_NAME LIKE '%Pampered Chef%'
OR EMPLOYER_NAME LIKE '%KitchFix%'
OR EMPLOYER_NAME LIKE '%GE Healthcare%'
OR EMPLOYER_NAME LIKE '%Motorola Solutions%'
OR EMPLOYER_NAME LIKE '%Gogo Business Aviation%'
OR EMPLOYER_NAME LIKE '%ActiveCampaign%'
OR EMPLOYER_NAME LIKE '%Aptitive%'
OR EMPLOYER_NAME LIKE '%Black Spectacles%'
OR EMPLOYER_NAME LIKE '%G2%'
OR EMPLOYER_NAME LIKE '%GoHealth%'
OR EMPLOYER_NAME LIKE '%Hireology%'
OR EMPLOYER_NAME LIKE '%Project44%'
OR EMPLOYER_NAME LIKE '%RedShelf%'
OR EMPLOYER_NAME LIKE '%Reverb%'
OR EMPLOYER_NAME LIKE '%ShopRunner%'
OR EMPLOYER_NAME LIKE '%Spot Hero%'
OR EMPLOYER_NAME LIKE '%Zoro%'
OR EMPLOYER_NAME LIKE '%Tropicana Brands Group%'
OR EMPLOYER_NAME LIKE '%Littlefuse%'
OR EMPLOYER_NAME LIKE '%Quaker Oats%'
OR EMPLOYER_NAME LIKE '%Mondelez International%'
OR EMPLOYER_NAME LIKE '%Amsted Industries%'
OR EMPLOYER_NAME LIKE '%John Crane %'
OR EMPLOYER_NAME LIKE '%JBT Corporation%'
OR EMPLOYER_NAME LIKE '%Coeur Mining, Inc%'
OR EMPLOYER_NAME LIKE '%Morton Salt%'
OR EMPLOYER_NAME LIKE '%Century Aluminum%'
OR EMPLOYER_NAME LIKE '%FoxTrot%'
OR EMPLOYER_NAME LIKE '%Feralloy Corporation %'
OR EMPLOYER_NAME LIKE '%Caterpillar%'
OR EMPLOYER_NAME LIKE '%Thoughtworks%'
OR EMPLOYER_NAME LIKE '%Wintrust Financial Corporation %'
OR EMPLOYER_NAME LIKE '%Northern Trust%'
OR EMPLOYER_NAME LIKE '%Rightpoint%'
OR EMPLOYER_NAME LIKE '%OCC%'
OR EMPLOYER_NAME LIKE '%CAN%'
OR EMPLOYER_NAME LIKE '%Echo Global Logistics %'
OR EMPLOYER_NAME LIKE '%Morningstar%'
OR EMPLOYER_NAME LIKE '%Ayden%'
OR EMPLOYER_NAME LIKE '%Tegus%'
OR EMPLOYER_NAME LIKE '%PatientPoint%'
OR EMPLOYER_NAME LIKE '%Walgreens%'
OR EMPLOYER_NAME LIKE '%Life Fitness%'
OR EMPLOYER_NAME LIKE '%Qualtrics%'
OR EMPLOYER_NAME LIKE '%Flexport%'
OR EMPLOYER_NAME LIKE '%Oak Street Health%'
OR EMPLOYER_NAME LIKE '%Relativity%'
OR EMPLOYER_NAME LIKE '%NielsenIQ%'
OR EMPLOYER_NAME LIKE '%Peapod Digital Labs%'
OR EMPLOYER_NAME LIKE '%Kin + Carta%'
OR EMPLOYER_NAME LIKE '%Grainger%'
OR EMPLOYER_NAME LIKE '%Enfusion%'
OR EMPLOYER_NAME LIKE '%Epsilon%'
OR EMPLOYER_NAME LIKE '%Netrix%'
OR EMPLOYER_NAME LIKE '%Capital One%'
OR EMPLOYER_NAME LIKE '%Enova%'
OR EMPLOYER_NAME LIKE '%United Airlines%'
OR EMPLOYER_NAME LIKE '%Transunion%'
OR EMPLOYER_NAME LIKE '%West Monroe%'
OR EMPLOYER_NAME LIKE '%Sg2%'
OR EMPLOYER_NAME LIKE '%Archer Daniels Midland%'
OR EMPLOYER_NAME LIKE '%Allstate%'
OR EMPLOYER_NAME LIKE '%Exelom%'
OR EMPLOYER_NAME LIKE '%AbbVie%'
OR EMPLOYER_NAME LIKE '%US Foods%'
OR EMPLOYER_NAME LIKE '%Abbott Labs%'
OR EMPLOYER_NAME LIKE '%Navistar%'
OR EMPLOYER_NAME LIKE '%Arthur Gallagher%'
OR EMPLOYER_NAME LIKE '%Bulley & Andrews%'
OR EMPLOYER_NAME LIKE '%Edward Hines Lumber Company%'
OR EMPLOYER_NAME LIKE '%Great Lakes Dredge and Dock Company%'
OR EMPLOYER_NAME LIKE '%James McHugh Construction Co%'
OR EMPLOYER_NAME LIKE '%Baird & Warner %'
OR EMPLOYER_NAME LIKE '%Brookfield Properties%'
OR EMPLOYER_NAME LIKE '%CenterPoint Properties%'
OR EMPLOYER_NAME LIKE '%Cushman & Wakefield%'
OR EMPLOYER_NAME LIKE '%EQ Office%'
OR EMPLOYER_NAME LIKE '%Equity Residential%'
OR EMPLOYER_NAME LIKE '%Fordham Company %'
OR EMPLOYER_NAME LIKE '%JMB Realty%'
OR EMPLOYER_NAME LIKE '%Jones Lang LaSalle%'
OR EMPLOYER_NAME LIKE '%Magellan Development Group%'
OR EMPLOYER_NAME LIKE '%Strategic Hotels & Resorts %'
OR EMPLOYER_NAME LIKE '%Ventas %'
OR EMPLOYER_NAME LIKE '%Lincoln International%'
OR EMPLOYER_NAME LIKE '%Mesirow Financial%'
OR EMPLOYER_NAME LIKE '%Nuveen Investment%'
OR EMPLOYER_NAME LIKE '%PTI Securities & Future%'
OR EMPLOYER_NAME LIKE '%William Blair & Company%'
OR EMPLOYER_NAME LIKE '%Harris Associates%'
OR EMPLOYER_NAME LIKE '%GTCR%'
OR EMPLOYER_NAME LIKE '%Madison Dearborn Partners%'
OR EMPLOYER_NAME LIKE '%Lake Capital%'
OR EMPLOYER_NAME LIKE '%CIVC Partners%'
OR EMPLOYER_NAME LIKE '%Transmarket Group%'
OR EMPLOYER_NAME LIKE '%Apple%'
OR EMPLOYER_NAME LIKE '%Amazon%'
OR EMPLOYER_NAME LIKE '%Ariel Investments%'
OR EMPLOYER_NAME LIKE '%Loop Capital%'
OR EMPLOYER_NAME LIKE '%Fidelity%'
OR EMPLOYER_NAME LIKE '%Microsoft%'
OR EMPLOYER_NAME LIKE '%Edgewater Funds%'
OR EMPLOYER_NAME LIKE '%NVIDIA%'
)
AND
E.RECORD_STATUS_CODE = 'A'
AND
E.DEATH_DT = '00000000'
AND
E.STATE_CODE = 'IL'
