CREATE OR REPLACE VIEW FSM_TRANSACTIONS_DM AS

WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

------ TRANSACTION FIELDS
SELECT DISTINCT
E.ID_NUMBER AS "ID Number",
E.REPORT_NAME AS "Report Name",
G.TRANS_ID_NUMBER AS "Transaction ID",
CASE
  WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC
  WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC
  ELSE T.TRANSACTION_TYPE_DESC END AS "Type of Transaction",
G.YEAR_OF_GIVING AS "Fiscal Year",
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Date(mmddyyyy)",
CASE
  WHEN EXTRACT(MONTH FROM TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) IN ('9','10','11') THEN 'Q1'
  WHEN EXTRACT(MONTH FROM TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) IN ('12','1','2') THEN 'Q2'
  WHEN EXTRACT(MONTH FROM TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) IN ('3','4','5') THEN 'Q3'
  WHEN EXTRACT(MONTH FROM TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) IN ('6','7','8') THEN 'Q4'
  ELSE '' END AS "Fiscal Quarter",
G.NEW_GIFTS_AND_CMIT_AMT AS "New Gifts and Commitments",
G.ENTIRE_AMOUNT AS "Entire Amount",
CASE
  WHEN TG.TRANSACTION_SUB_GROUP_CODE IN ('GC') THEN G.OUTRIGHT_GIFT_AMOUNT
  WHEN TG.TRANSACTION_SUB_GROUP_CODE IN ('YC') THEN G.PLEDGE_PAYMENT_AMOUNT
  WHEN TG.TRANSACTION_SUB_GROUP_CODE IN ('MC') THEN G.MATCHING_GIFT_AMOUNT
  ELSE 0.00 END AS "Cash",
G.GIFT_CREDIT_AMOUNT AS "Gift Credit Amount",
A.APPEAL_CODE AS "Appeal Code",
A.Description AS "Appeal Description",
A.APPEAL_GROUP_CODE AS "Appeal Group Code",
A.APPEAL_GROUP_DESC AS "Appeal Group Descr",
A.APPEAL_TYPE_CODE AS "Appeal Type Code",
A.APPEAL_TYPE_DESC AS "Appeal Type Descr",
A.PROGRAM_CODE AS "Appeal Program Code",
A.PROGRAM_CODE_DESC AS "Appeal Program Descr",
AL.ALLOCATION_CODE AS "Allocation Code",
AL.ALLOC_SHORT_NAME AS "Allocation Short Name",
AL.LONG_NAME AS "Allocation Long Name",
AL.RESTRICT_DESC AS "Alloc Restricted",
AL.FUND_NAME AS "Alloc Fund Name",
AL.FUND_DESC AS "Alloc Fund Descr",
AL.PROGRAM_CODE AS "Alloc Program Code",
AL.PROGRAM_DESC AS "Alloc Program Descr",
AL.ALLOC_DEPT_CODE AS "Alloc Dept Code",
AL.ALLOC_DEPT_DESC AS "Alloc Dept Descr",
AL.AGENCY_CODE AS "Tier 1 Purpose Code",
AL.AGENCY_CODE_DESC AS "Tier 1 Purpose Descr",
AL.ALLOC_PURPOSE_CODE AS "Tier 2 Purpose Code",
AL.ALLOC_PURPOSE_DESC AS "Tier 2 Purpose Descr",
RA.REPORTING_AREA_FULL_DESC AS "Reporting Area Long Name",
GA.GIFT_ASSOCIATED_CODE AS "Gift Associated Code",
GA.GIFT_ASSOCIATED_DESC AS "Gift Associated Descr",
G.PROPOSAL_ID AS "Proposal ID",
P.PROPOSAL_MANAGER_NAME AS "Proposal Manager",


------ CONSTITUENT FIELDS
E.PRIMARY_RECORD_TYPE_DESC AS "Record Type Descr",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
--CASE WHEN E.BIRTH_DT <> '00000000' THEN TRUNC((SYSDATE - TO_DATE(E.BIRTH_DT, 'YYYY-MM-DD'))/ 365.25) ELSE 0 END AS "Age",
E.INSTITUTIONAL_SUFFIX AS "Institutional Suffix",
E.SALUTATION AS "Salutation",
E.LAST_NAME AS "Last Name",
E.FIRST_NAME AS "First Name",
E.GENDER_CODE AS "Gender",
E.PREF_CLASS_YEAR AS "Preferred Class Year",
E.PREF_SCHOOL_CODE AS "Preferred School Code",
E.PREF_SCHOOL_NAME AS "Preferred School Name",
E.RECORD_STATUS_CODE AS "Record Status Code",
E.RECORD_STATUS_DESC AS "Record Status Descr",
CASE WHEN E.DEATH_DT <> '00000000' THEN 'Y' ELSE 'N' END AS "Deceased",
E.ADDRESS_STREET1 AS "Address Line 1",
E.ADDRESS_STREET2 AS "Address Line 2",
E.CITY AS "City",
E.STATE_CODE AS "ST",
SUBSTR(E.ZIPCODE,1,5) AS "ZIP",
E.COUNTRY_NAME AS "Country",
EMAIL_ADDRESS AS "Email",
CASE WHEN LENGTH(PHONE_AREA_CODE) = 3 AND LENGTH(PHONE_NUMBER) = 7 THEN '(' || E.PHONE_AREA_CODE || ') ' || SUBSTR(E.PHONE_NUMBER,1,3) || '-' || SUBSTR(E.PHONE_NUMBER,4,4) ELSE E.PHONE_NUMBER END AS "Phone",
PR.PROSPECT_MANAGER_NAME AS "Prospect Manager",
--PR.PROSPECT_TEAM_DESC AS "Prospect Team",
FDS.LIFETIME_GIFT_CREDIT_AMOUNT AS "Lifetime Giving",
FDSF.LIFETIME_GIFT_CREDIT_AMOUNT AS "FSM Lifetime Giving",
PR.RATING_DESC AS "Wealth Rating",
E.MAJOR_GIFT_PR_TIER AS "Major Gift Tier",
E.AFFINITY_SCORE AS "Affinity Score",
SHS.DO_NOT_SOLICIT_FLAG AS "Do Not Solicit",
SHS.DO_NOT_MAIL_FLAG AS "Do Not Mail",
SHS.DO_NOT_EMAIL_FLAG AS "Do Not Email"

FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON G.ENTITY_ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_REPORTING_AREA@catrackstobi RA ON G.REPORTING_AREA_SID = RA.REPORTING_AREA_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
LEFT OUTER JOIN DM_ARD.DIM_GIFT_ASSOCIATION@catrackstobi GA ON G.GIFT_ASSOCIATED_SID = GA.GIFT_ASSOCIATED_SID
LEFT OUTER JOIN DM_ARD.DIM_PROPOSAL@catrackstobi P ON G.PROPOSAL_ID = P.PROPOSAL_ID AND P.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_SPECIAL_HANDLING_SUMMARY@catrackstobi SHS ON E.ID_NUMBER = SHS.ID_NUMBER
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDS ON E.ID_NUMBER = FDS.ENTITY_KEY AND FDS.ANNUAL_FUND_FLAG = 'N' AND FDS.REPORTING_AREA = 'NA' 
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDSF ON E.ID_NUMBER = FDSF.ENTITY_KEY AND FDSF.ANNUAL_FUND_FLAG = 'N' AND FDSF.REPORTING_AREA = 'FS' 
LEFT OUTER JOIN CURRENT_FY ON FDS.FISCAL_YEAR = CFY AND FDSF.FISCAL_YEAR = CFY 
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT_ENTITY@catrackstobi PE ON E.ID_NUMBER = PE.ID_NUMBER AND PE.CURRENT_INDICATOR = 'Y' AND PE.PROSPECT_ACTIVE_IND = 'Y' AND PE.DELETED_FLAG = 'N'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT@catrackstobi PR ON PE.PROSPECT_ID = PR.PROSPECT_ID AND PR.CURRENT_INDICATOR = 'Y'
WHERE
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
GA.GIFT_ASSOCIATED_CODE NOT IN (/*'C',*/'H','M') -- EXCLUDE SOFT CREDITS, IMO, IHO
--AND
--G.APPEAL_SID NOT IN (17710,17711) ----- EXCLUDE AFFIL, HOSPF, BLANK APPEALS
;
