CREATE OR REPLACE VIEW RPT_RVA7647.FSM_PROPOSALS_DM AS

SELECT
A.*,
ROW_NUMBER() OVER (PARTITION BY A."Prospect ID" ORDER BY A."Active" DESC, A."Proposal Start Date" DESC) AS Rw
FROM
(
SELECT DISTINCT
PR.PROSPECT_ID AS "Prospect ID",
PR.PROSPECT_NAME AS "Prospect Name",

-----PROPOSAL INFO
P.PROPOSAL_ID AS "Proposal ID",
P.ACTIVE_IND AS "Active",
P.PROPOSAL_TITLE AS "Proposal Title",
P.DESCRIPTION AS "Proposal Description",
P.PROPOSAL_STATUS_CODE AS "Proposal Status Code",
P.PROPOSAL_STATUS_DESC AS "Proposal Status Desc",
CASE WHEN P.START_DATE_KEY = 0 THEN 18000101 ELSE P.START_DATE_KEY END AS "Proposal Start Date",
CASE WHEN P.INITIAL_CONTRIBUTION_DATE_KEY = 0 THEN 18000101 ELSE P.INITIAL_CONTRIBUTION_DATE_KEY END AS "Ask Date",
CASE WHEN P.STOP_DATE_KEY = 0 THEN 18000101 ELSE P.STOP_DATE_KEY END AS "Proposal Close Date",
P.PROPOSAL_TYPE AS "Proposal Type Code",
P.PROPOSAL_TYPE_DESC AS "Proposal Type Desc",
P.ORIGINAL_ASK_AMT AS "Original Ask Amount",
P.ANTICIPATED_AMT AS "Anticipated Amount",
P.ASK_AMT AS "Ask Amount",
P.GRANTED_AMT AS "Granted Amount",
P.FUNDING_TYPE AS "Funding Type Code",
P.FUNDING_TYPE_DESC AS "Funding Type Desc",
P.SUBMIT_TYPE AS "Submit Type Code",
P.SUBMIT_TYPE_DESC AS "Submit Type Desc",
P.PROPOSAL_STATUS_CATEGORY AS "Proposal Status Category",
P.PROPOSAL_PROGRAM_LIST AS "Program List",

-----PROPOSAL MANAGER INFO
P.PROPOSAL_MANAGER_ID_NUMBER AS "Proposal Manager ID",
P.PROPOSAL_MANAGER_NAME AS "Proposal Manager Name",
P.PROPOSAL_MANAGER_NAMES_ALL AS "All Proposal Manager Names",

-----GIFT OFFICER HIERARCHY
FH."Vice Dean",
FH."Vice Dean netID",
FH."Team",
FH."Team netID",
FH."Sub-Team",
FH."Sub-Team netID",
FH."Gift Officer",
FH."Gift Officer netID",
E.PREF_MAIL_NAME AS "Gift Officer Preferred Name",

-----RESULTING TRANSACTION DATA
P.RESULTING_TRANSACTION_ID AS "Transaction ID",
P.RESULTING_TRANSACTION_DESC AS "Transaction Detail",
P.RESULTING_TRANSACTION_ALLOC AS "Transaction Allocation"

FROM DM_ARD.DIM_PROPOSAL@catrackstobi P
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT@catrackstobi PR ON P.PROSPECT_ID = PR.PROSPECT_ID AND PR.CURRENT_INDICATOR = 'Y' AND PR.DELETED_FLAG = 'N'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT_ENTITY@catrackstobi PE ON PR.PROSPECT_ID = PE.PROSPECT_ID AND PE.CURRENT_INDICATOR = 'Y' AND PE.PROSPECT_ACTIVE_IND = 'Y' AND PE.DELETED_FLAG = 'N'
LEFT OUTER JOIN FSM_HIERARCHY FH ON FH."ID Number" = P.PROPOSAL_MANAGER_ID_NUMBER
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON FH."ID Number" = E.ID_NUMBER AND E.DELETED_FLAG = 'N' AND E.CURRENT_INDICATOR = 'Y'

WHERE
P.CURRENT_INDICATOR = 'Y'
AND
P.DELETED_FLAG = 'N'
AND
P.OFFICE_CODE = 'FS' ---- FEINBERG
) A
