SELECT DISTINCT
ALLOC_DEPT_CODE,
ALLOC_DEPT_SHORT_DESC,
ALLOC_DEPT_DESC

FROM DM_ARD.DIM_ALLOCATION@catrackstobi
WHERE
ALLOC_SCHOOL = 'FS'
AND
ALLOC_STATUS_CODE = 'A'
AND
CURRENT_INDICATOR = 'Y'
ORDER BY
ALLOC_DEPT_DESC
