SELECT
*
FROM gift
where
gift_donor_id = '0000819254'


SELECT 
G.GIFT_DONOR_ID,
G.GIFT_RECEIPT_NUMBER,
G.GIFT_SEQUENCE,
GC.GIFT_CODE,
GC.GIFT_COMMENT
FROM GIFT G
INNER JOIN GIFT_CODES GC ON G.GIFT_RECEIPT_NUMBER = GC.RECEIPT_NUMBER, ALLOCATION
WHERE 
TO_CHAR(GIFT_DATE_OF_RECORD) >= '2017-01-01'
AND 
GIFT_ASSOCIATED_AMOUNT > 0 -- CaTracks query removes $0 H/M donors
AND 
GIFT_ASSOCIATED_ALLOCATION = ALLOCATION_CODE
AND
ALLOC_SCHOOL = 'FS'
AND 
GC.GIFT_CODE IN ('H')
AND
GC.GIFT_COMMENT LIKE '%GALLON%'
