WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT
E.ID_NUMBER AS "ID Number",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
G.TRANS_ID_NUMBER AS "Transaction ID",
CASE WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC ELSE T.TRANSACTION_TYPE_DESC END AS "Type of Transaction",
SUBSTR(CONCAT('0000000000',G.PROPOSAL_ID),-10) AS "Proposal ID",
P.PROPOSAL_MANAGER_ID_NUMBER ,
P.PROPOSAL_MANAGER_NAME AS "Proposal Manager",
G.YEAR_OF_GIVING AS "Fiscal Year",
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Date(mmddyyyy)", 
G.NEW_GIFTS_AND_CMIT_AMT AS "New Gifts and Commitments",
AL.ALLOCATION_CODE AS "Allocation Code",
AL.LONG_NAME AS "Allocation Short Name",
A.APPEAL_CODE AS "Appeal Code",
PR.PROSPECT_MANAGER_NAME AS "Prospect Manager"
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON G.ENTITY_ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_REPORTING_AREA@catrackstobi RA ON G.REPORTING_AREA_SID = RA.REPORTING_AREA_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID 
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
LEFT OUTER JOIN DM_ARD.DIM_PROPOSAL@catrackstobi P ON G.PROPOSAL_ID = P.PROPOSAL_ID AND P.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT_ENTITY@catrackstobi PE ON E.ID_NUMBER = PE.ID_NUMBER AND PE.CURRENT_INDICATOR = 'Y' AND PE.PROSPECT_ACTIVE_IND = 'Y' AND PE.DELETED_FLAG = 'N'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT@catrackstobi PR ON PE.PROSPECT_ID = PR.PROSPECT_ID AND PR.CURRENT_INDICATOR = 'Y'
WHERE
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
G.APPEAL_SID NOT IN (17710,17711) ----- EXCLUDE AFFIL, HOSPF, BLANK APPEALS
AND
P.PROPOSAL_MANAGER_ID_NUMBER = '0000783839'
AND
G.ENTIRE_AMOUNT > 50000
AND
G.NEW_GIFTS_AND_CMIT_AMT > 0


ORDER BY
G.NEW_GIFTS_AND_CMIT_AMT DESC
