WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT DISTINCT
C.ID_NUMBER AS "CATracks ID",
E2.PREF_MAIL_NAME AS "Contacted Name",
SUBSTR(CONCAT('0000000000',C.REPORT_ID),-10) AS "Report ID",
TMS_CTYPE.short_desc AS "Contact Type",
TMS_CPURP.short_desc AS "Contact Purpose",
C.CONTACT_DATE AS "Contact Date",
C.DESCRIPTION AS "Description",
CASE WHEN (SELECT COUNT(DISTINCT ID_NUMBER) FROM ADVANCE.CONTACT_RPT_CREDIT CRC WHERE CRC.REPORT_ID = C.REPORT_ID) > 1 THEN '2 credit entities' ELSE E.PREF_MAIL_NAME END AS "Credit Name"

FROM CONTACT_REPORT C
INNER JOIN CURRENT_FY ON CASE WHEN EXTRACT(MONTH FROM C.CONTACT_DATE) >= 9 THEN EXTRACT(YEAR FROM C.CONTACT_DATE)+1 ELSE EXTRACT(YEAR FROM C.CONTACT_DATE) END = CURRENT_FY.CFY
INNER JOIN FSM_DAR_STAFF ON C.AUTHOR_ID_NUMBER = FSM_DAR_STAFF.ID_NUMBER
INNER JOIN ENTITY E ON FSM_DAR_STAFF.ID_NUMBER = E.ID_NUMBER
INNER JOIN ENTITY E2 ON C.ID_NUMBER = E2.ID_NUMBER
INNER JOIN tms_contact_rpt_purpose tms_cpurp On tms_cpurp.contact_purpose_code = c.contact_purpose_code
INNER JOIN tms_contact_rpt_type tms_ctype On tms_ctype.contact_type = c.contact_type

WHERE
C.AUTHOR_ID_NUMBER = '0000783839'

ORDER BY
C.CONTACT_DATE DESC
