WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT DISTINCT
N.ID_NUMBER AS "ID Number",
E2.PREF_MAIL_NAME AS "Name",
N.NOTE_DATE AS "Date",
e.report_name As "Author",
N.DESCRIPTION AS "Description"
FROM NOTES N
INNER JOIN CURRENT_FY ON CASE WHEN EXTRACT(MONTH FROM N.NOTE_DATE) >= 9 THEN EXTRACT(YEAR FROM N.NOTE_DATE)+1 ELSE EXTRACT(YEAR FROM N.NOTE_DATE) END = CURRENT_FY.CFY
INNER JOIN FSM_DAR_STAFF ON N.AUTHOR_ID_NUMBER = FSM_DAR_STAFF.ID_NUMBER
INNER JOIN ENTITY E ON N.AUTHOR_ID_NUMBER = E.ID_NUMBER
INNER JOIN ENTITY E2 ON N.ID_NUMBER = E2.ID_NUMBER
Inner Join tms_note_type tms_ntype On tms_ntype.note_type = n.note_type

WHERE
N.AUTHOR_ID_NUMBER = '0000783839';
