---- ADDRESS TYPES
SELECT DISTINCT
A.ADDR_TYPE_CODE,
T.long_desc AS "Addr Type Desc"
FROM ADDRESS A
LEFT OUTER JOIN ADVANCE.TMS_ADDRESS_TYPE T ON A.ADDR_TYPE_CODE = T.ADDR_TYPE_CODE
ORDER BY
A.ADDR_TYPE_CODE


---- ADDRESS SOURCE CODES
SELECT DISTINCT
A.ADDR_SRC_CODE,
T.SHORT_desc AS "Addr Src Desc"
FROM ADDRESS A
LEFT OUTER JOIN ADVANCE.TMS_ADDR_SRC T ON A.ADDR_SRC_CODE = T.ADDR_SRC_CODE
ORDER BY
A.ADDR_SRC_CODE


---- ADDRESS STATUSES
SELECT DISTINCT
A.ADDR_STATUS_CODE,
T.SHORT_desc AS "Addr Status Desc"
FROM ADDRESS A
LEFT OUTER JOIN ADVANCE.TMS_ADDR_STATUS T ON A.ADDR_STATUS_CODE = T.ADDR_STATUS_CODE
ORDER BY
A.ADDR_STATUS_CODE


---- ADDRESS CODES
SELECT DISTINCT
A.ADDRESS_CODE,
T.SHORT_desc AS "Addr Status Desc"
FROM ADDRESS A
LEFT OUTER JOIN ADVANCE.TMS_ADDRESS_CODE T ON A.ADDRESS_CODE = T.ADDRESS_CODE
ORDER BY
A.ADDRESS_CODE
