---- SCHOOLS
SELECT DISTINCT
D.SCHOOL_CODE,
T.long_desc AS "School Description"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_SCHOOL t ON D.SCHOOL_CODE = T.SCHOOL_CODE
ORDER BY
SCHOOL_CODE

---- DEGREE TYPES
SELECT DISTINCT
D.DEGREE_TYPE AS "Degree Code",
T.full_desc AS "Degree Code Description"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_DEGREE_TYPE T ON D.DEGREE_TYPE = T.degree_type_code
ORDER BY
DEGREE_TYPE


---- DEPARTMENTS
SELECT DISTINCT
D.DEPT_CODE,
T.full_desc AS "Department Desc"
FROM Degrees D
LEFT OUTER JOIN ADVANCE.TMS_DEPT_CODE T ON D.DEPT_CODE = T.DEPT_CODE
ORDER BY
DEPT_CODE


---- DIVISIONS
SELECT DISTINCT
D.DIVISION_CODE,
T.FULL_desc AS "Division Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_DIVISION T ON D.DIVISION_CODE = T.DIVISION_CODE
ORDER BY
D.DIVISION_CODE

---- MAJORS
SELECT DISTINCT
D.MAJOR_CODE1,
T.FULL_DESC AS "Major Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_MAJORS T ON D.MAJOR_CODE1 = T.MAJOR_CODE
ORDER BY
D.MAJOR_CODE1

---- CONCENTRATIONS
SELECT DISTINCT
D.CONCENTRATION_CODE ,
T.FULL_DESC AS "Concentration Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_CONCENTRATION T ON D.CONCENTRATION_CODE = T.CONCENTRATION_CODE
ORDER BY
CONCENTRATION_CODE

---- FINANCIAL AID
SELECT DISTINCT
D.FINANCIAL_AID_CODE ,
T.SHORT_DESC AS "Financial Aid Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_FINANCIAL_AID T ON D.FINANCIAL_AID_CODE = T.FINANCIAL_AID_CODE
ORDER BY
FINANCIAL_AID_CODE


---- DEGREE LEVELS
SELECT DISTINCT
D.DEGREE_LEVEL_CODE,
T.short_desc AS "Degree Level Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_DEGREE_LEVEL T ON D.DEGREE_LEVEL_CODE = T.DEGREE_LEVEL_CODE
ORDER BY
D.DEGREE_LEVEL_CODE

---- CAMPUSES
SELECT DISTINCT
D.CAMPUS_CODE,
T.short_desc AS "Campus Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_CAMPUS T ON D.CAMPUS_CODE = T.CAMPUS_CODE
ORDER BY
D.CAMPUS_CODE


---- DEGREE CODES
SELECT DISTINCT
D.DEGREE_CODE,
T.FULL_DESC AS "Degree Code Desc"
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_DEGREES T ON D.DEGREE_CODE = T.DEGREE_CODE
ORDER BY
D.DEGREE_CODE



