---- ENTITIES
SELECT
*
FROM ENTITY E
--FETCH FIRST 100 ROWS ONLY


---- ADDRESSES
SELECT
*
FROM ADDRESS E
--FETCH FIRST 100 ROWS ONLY


---- DEGREES
SELECT
*
FROM DEGREES D
--FETCH FIRST 100 ROWS ONLY


---- COMBINING ALL THREE TABLES (ENTITIES, ADDRESSES, DEGREES)
SELECT
E.ID_NUMBER,
E.PERSON_OR_ORG,
E.FIRST_NAME,
E.LAST_NAME,
A.STREET1,
A.STREET2,
A.STREET3,
A.CITY,
A.STATE_CODE,
A.ZIPCODE,
D.SCHOOL_CODE AS "School",
D.DEGREE_YEAR AS "Grad Year"
FROM ENTITY E
LEFT OUTER JOIN ADDRESS A ON E.ID_NUMBER = A.ID_NUMBER
LEFT OUTER JOIN DEGREES D ON E.ID_NUMBER = D.ID_NUMBER
WHERE
PERSON_OR_ORG = 'P'
AND
D.SCHOOL_CODE = 'MED'

