---- PROSPECTS
SELECT
*
FROM PROSPECT


---- PROPOSALS
SELECT
*
FROM PROPOSAL


---- COMBINED
SELECT
E.ID_NUMBER,
E.LAST_NAME,
E.FIRST_NAME,
D.DEGREE_YEAR,
PR.*,
P.*
FROM ENTITY E
INNER JOIN PROSPECT_ENTITY PE ON E.ID_NUMBER = PE.ID_NUMBER
INNER JOIN PROSPECT PR ON PE.PROSPECT_ID = PR.PROSPECT_ID
INNER JOIN PROPOSAL P ON PE.PROSPECT_ID = P.PROSPECT_ID
INNER JOIN DEGREES D ON E.ID_NUMBER = D.ID_NUMBER AND D.SCHOOL_CODE = 'MED'

