SELECT
*
FROM RPT_PBH634.V_PROPOSAL_HISTORY_FAST T
WHERE 
T.proposal_manager_ID IN (
SELECT
E.ID_NUMBER
--E.LAST_NAME,
--E.FIRST_NAME,
--EM.EMPLOYER_UNIT
FROM --ADVANCE.AFFILIATION T
--INNER JOIN 
ENTITY E --ON T.ID_NUMBER = E.ID_NUMBER
INNER JOIN EMPLOYMENT EM ON E.ID_NUMBER = EM.ID_NUMBER AND EM.JOB_STATUS_CODE = 'C' AND (EM.EMPLOYER_UNIT = 'MED-NU-FSM Off of Dev & Alumni' OR EM.EMPLOYER_NAME1 = 'NU Feinberg Development and Alumni Relations')
)
AND
PROPOSAL_ACTIVE_CALC = 'Active'
AND
CLOSE_FY = '2024'
AND
TOTAL_ANTICIPATED_AMT >= 100000
/*AND
CLOSE_DATE <= '13-DEC-23'*/
AND
SUBSTR(PROBABILITY,1,2) > 50

ORDER BY
TOTAL_ASK_AMT DESC,
Prospect_Name
