SELECT
E.ID_NUMBER AS "ID Number",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
P.PROPOSAL_ID,
P.PROPOSAL_STATUS_DESC AS "Proposal Status",
p.*
FROM DM_ARD.DIM_PROPOSAL@catrackstobi P
INNER JOIN RPT_RVA7647.FSM_DAR_STAFF DAR ON P.PROPOSAL_MANAGER_ID_NUMBER = DAR.ID_NUMBER
INNER JOIN DM_ARD.DIM_PROSPECT@catrackstobi PR ON P.PROSPECT_ID = PR.PROSPECT_ID AND PR.CURRENT_INDICATOR = 'Y' AND PR.DELETED_FLAG = 'N'
INNER JOIN PROSPECT_ENTITY PE ON PR.PROSPECT_ID = PE.PROSPECT_ID 
INNER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON PE.ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'

WHERE
P.CURRENT_INDICATOR = 'Y' 
AND 
P.DELETED_FLAG = 'N'
