SELECT
*
FROM DM_ARD.DIM_APPEAL@catrackstobi
WHERE
--DESCRIPTION LIKE '%LCC%'
--AND
DESCRIPTION LIKE 'FY24%'
AND
APPEAL_TYPE_CODE = 'D'
AND
PROGRAM_CODE = 'FS'
AND
APPEAL_GROUP_CODE = 'FSG'
