CREATE OR REPLACE VIEW RPT_RVA7647.FSM_GP_AG_STATS AS

WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
),

APP_COUNTS AS (
SELECT
A.N_APPEAL_CODE,
A.APPEAL_CTGRY,
COUNT(DISTINCT CASE WHEN A.ID_NUMBER IS NOT NULL THEN A.ID_NUMBER ELSE A.FSM_ID END) AS "Number of Recipients",
A.FISCAL_YEAR
FROM FSM_GP_APPEAL_DATA A
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON AP.APPEAL_CODE = A.N_APPEAL_CODE
GROUP BY
A.N_APPEAL_CODE,
A.FISCAL_YEAR
),

GIFTS AS (
SELECT DISTINCT
AP.APPEAL_CODE AS "Appeal Code",
AP.DESCRIPTION AS "Appeal Description",
G.APPEAL_SID,
G.ENTITY_ID_NUMBER,
G.TRANS_ID_NUMBER,
G.DATE_OF_RECORD_KEY AS "Gift Date"
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON G.APPEAL_SID = AP.APPEAL_SID
INNER JOIN APP_COUNTS A ON AP.APPEAL_CODE = A.N_APPEAL_CODE

WHERE
G.NEW_GIFTS_AND_CMIT_AMT > 0
),

/*
NOAPL AS (
SELECT DISTINCT
A."Appeal Code",
A."Appeal Description",
A."Appeal Category",
AP.APPEAL_SID,
A."Appeal Date",
G.ENTITY_ID_NUMBER,
G.TRANS_ID_NUMBER,
G.DATE_OF_RECORD_KEY AS "Gift Date",
CASE WHEN G2.ENTITY_ID_NUMBER IS NOT NULL THEN G2.NEW_GIFTS_AND_CMIT_AMT ELSE G.NEW_GIFTS_AND_CMIT_AMT END AS "Gift Amount",
A."Fiscal Year"
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN APP_SENDS A ON A.ID_NUMBER = G.ENTITY_ID_NUMBER AND G.YEAR_OF_GIVING = A."Fiscal Year" AND A."Appeal Category" NOT IN ('Grateful Patients')
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON AP.APPEAL_SID = G.APPEAL_SID
INNER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID AND AL.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.TRANS_ID_NUMBER = G2.TRANS_ID_NUMBER AND G2.GIFT_ASSOCIATED_SID = '3' AND G.GIFT_ASSOCIATED_SID <> '3'

WHERE
AP.APPEAL_CODE = 'NOAPL'
AND
AL.ALLOCATION_CODE IN (
'3203000890801GFT',
'3203000905701GFT',
'3203000908201GFT',
'3203000916501GFT',
'3203000934001GFT',
'3203000951901GFT',
'3203002191001GFT',
'3203002581901GFT',
'3203002619701GFT',
'3203002637401GFT',
'3203002761501GFT',
'3203002763601GFT',
'3203002852301GFT',
'3203002879401GFT',
'3203002921701GFT',
'3203003023001GFT',
'3203003034901GFT',
'3203003035001GFT',
'3203003059401GFT',
'3203003060401GFT',
'3203003076701GFT',
'3203003116301GFT',
'3203003122401GFT',
'3203003155201GFT',
'3203003159101GFT',
'3203003317301GFT',
'3203003536101GFT',
'3203003625101GFT',
'3203003750101GFT',
'3203003914701GFT',
'3203003952701GFT',
'3203004172501GFT',
'3203004272601GFT',
'3203004686701GFT',
'3203005213501GFT',
'3203002116501GFT'
)
AND
CASE WHEN G2.ENTITY_ID_NUMBER IS NOT NULL THEN G2.NEW_GIFTS_AND_CMIT_AMT ELSE G.NEW_GIFTS_AND_CMIT_AMT END > 0
),
*/

FTD AS (
SELECT DISTINCT
G.ENTITY_ID_NUMBER
FROM GIFTS G
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.ENTITY_ID_NUMBER = G2.ENTITY_ID_NUMBER
     AND G2.NEW_GIFTS_AND_CMIT_AMT > 0 AND G2.REPORTING_AREA_SID = '21' AND TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G."Gift Date",'YYYYMMDD')

WHERE
G2.ENTITY_ID_NUMBER IS NULL
),

RD AS (
SELECT DISTINCT
G.ENTITY_ID_NUMBER
FROM GIFTS G
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.ENTITY_ID_NUMBER = G2.ENTITY_ID_NUMBER
     AND G2.NEW_GIFTS_AND_CMIT_AMT > 0 AND G2.REPORTING_AREA_SID = '21'
     AND TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G."Gift Date",'YYYYMMDD')
     AND MONTHS_BETWEEN(TO_DATE(G."Gift Date",'YYYYMMDD'),TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD')) <= 60
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G3 ON G.ENTITY_ID_NUMBER = G3.ENTITY_ID_NUMBER
     AND G3.NEW_GIFTS_AND_CMIT_AMT > 0 AND G3.REPORTING_AREA_SID = '21'
     AND TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G."Gift Date",'YYYYMMDD')
     AND MONTHS_BETWEEN(TO_DATE(G."Gift Date",'YYYYMMDD'),TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD')) > 60
     AND G2.ENTITY_ID_NUMBER IS NULL
WHERE
G3.ENTITY_ID_NUMBER IS NOT NULL
)


SELECT
AP.APPEAL_CODE AS "Appeal Code",
AP.DESCRIPTION AS "Appeal Description",
G.APPEAL_SID,
AP.DATE_ADDED AS "Appeal Date",
A.FISCAL_YEAR AS "Fiscal Year",
A."Number of Recipients",
COUNT(DISTINCT G.TRANS_ID_NUMBER) AS "Number of Gifts",
COUNT(DISTINCT G.ENTITY_ID_NUMBER) AS "Number of Donors",
SUM(G.NEW_GIFTS_AND_CMIT_AMT) AS "Amount Raised",
LTRIM(TO_CHAR(AVG(G.NEW_GIFTS_AND_CMIT_AMT),'99999999.99')) AS "Average Gift Amount"

FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
--INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON G.APPEAL_SID = AP.APPEAL_SID
INNER JOIN APP_COUNTS A ON AP.APPEAL_CODE = A.N_APPEAL_CODE

WHERE
G.NEW_GIFTS_AND_CMIT_AMT > 0

GROUP BY
G.APPEAL_SID,
AP.APPEAL_CODE,
AP.DESCRIPTION,
AP.DATE_ADDED,
A."Number of Recipients",
A.FISCAL_YEAR


SELECT DISTINCT
S."Appeal Code",
S."Appeal Description",
S."Appeal Date",
S."Fiscal Year",
S."Number of Recipients",
S."Number of Gifts",
S."Number of Donors",
S."Number of Donors" / S."Number of Recipients" AS "Response Rate",
NVL(FTD."Number of New Donors",0) AS "Number of New Donors",
NVL(RD."Number of Reactivated Donors",0) AS "Number of Reactivated Donors",
S."Amount Raised",
S."Average Gift Amount"

FROM SUMS S
LEFT OUTER JOIN FTD ON S."Appeal Code" = FTD."Appeal Code"
LEFT OUTER JOIN RD ON S."Appeal Code" = RD."Appeal Code"

;
