----- Cancer Center
SELECT
APPEAL_CODE,
DESCRIPTION
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE 
(DESCRIPTION LIKE '%Lurie%' OR DESCRIPTION LIKE '%LCC CYE%' /*OR DESCRIPTION LIKE '% CYE %'*/)
AND
APPEAL_TYPE_CODE = 'E'
AND
APPEAL_CODE NOT IN ('NUEG1')

UNION

----- Grateful Patients
SELECT
*
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE 
APPEAL_TYPE_CODE = 'E'
AND
APPEAL_GROUP_DESC = 'FSM Departments'
--AND
--DESCRIPTION LIKE '%Grateful Patient%'
AND
DESCRIPTION LIKE 'FY21%'
AND
APPEAL_CODE NOT IN ('LFGFA','LFGD2')
ORDER BY
DESCRIPTION


----- Grateful Patients
SELECT
*
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE 
APPEAL_TYPE_CODE = 'E'
AND
APPEAL_GROUP_DESC = 'FSM Departments'
AND
DESCRIPTION LIKE 'FY%'
ORDER BY
DESCRIPTION
