----- Cancer Center Email Appeals
SELECT DISTINCT
APPEAL_SID,
APPEAL_CODE AS "Appeal Code",
DESCRIPTION AS "Appeal Description",
'Cancer Team' AS "Appeal Category",
'Email' AS "Appeal Type",
COALESCE((SELECT MIN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G WHERE G.APPEAL_SID = A.APPEAL_SID),TO_DATE(A.DATE_ADDED)) AS "Appeal Date",
CAST('20' || REPLACE(SUBSTR(DESCRIPTION,1,4),'FY','')AS INT) AS "Fiscal Year"
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE 
(DESCRIPTION LIKE '%Lurie%' OR DESCRIPTION LIKE '%LCC CYE%' /*OR DESCRIPTION LIKE '% CYE %'*/)
AND
APPEAL_TYPE_CODE = 'E'
AND
APPEAL_CODE NOT IN ('NUEG1')


----- Cancer Center Email Appeals
SELECT DISTINCT
APPEAL_SID,
APPEAL_CODE AS "Appeal Code",
DESCRIPTION AS "Appeal Description",
'Cancer Team' AS "Appeal Category",
'Email' AS "Appeal Type",
COALESCE((SELECT MIN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')) FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G WHERE G.APPEAL_SID = A.APPEAL_SID),TO_DATE(A.DATE_ADDED)) AS "Appeal Date",
CAST('20' || REPLACE(SUBSTR(DESCRIPTION,1,4),'FY','')AS INT) AS "Fiscal Year"
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE 
(DESCRIPTION LIKE '%DGP%')
AND
APPEAL_TYPE_CODE = 'E'
AND
APPEAL_CODE NOT IN ('NUEG1')


SELECT
*
FROM DM_ARD.DIM_APPEAL@catrackstobi A
WHERE
APPEAL_CODE = 'NUEGA'
PROGRAM_CODE = 'FS'
AND
DESCRIPTION LIKE 'FY24%'
AND
APPEAL_TYPE_CODE = 'E'

SELECT
*
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
WHERE
APPEAL_SID = '27965'
