SELECT DISTINCT 
*
FROM ADVANCE_NU_RPT.ENCOMPASS_MESSAGES E
WHERE
SUB_COMMUNITY_ID = 6
AND
CATEGORY_NAME NOT IN ('Northwestern Medicine Magazine')

AND
(EMAIL_NAME LIKE '%grateful-patient%' OR EMAIL_NAME LIKE '%grateful%' OR EMAIL_NAME LIKE '%gp%' OR EMAIL_NAME LIKE '%acquisition%' OR FROM_NAME LIKE '%Feinberg Development%')
--(EMAIL_NAME LIKE '%LCC%' OR EMAIL_NAME LIKE '%cancer%' OR EMAIL_NAME LIKE '%Lurie%' OR EMAIL_NAME LIKE '%lurie%' OR EMAIL_NAME LIKE '%Cancer%' )
ORDER BY
ACTUAL_SEND_TIMESTAMP
--CAST(SENT_COUNT AS INT)DESC;
