CREATE OR REPLACE VIEW RPT_RVA7647.FSM_PG_PROSPECTS AS

SELECT
E.ID_NUMBER AS "ID Number",
E.REPORT_NAME as "Prospect Name",
E.LAST_NAME AS "Last Name",
E.FIRST_NAME AS "First Name",
E.INSTITUTIONAL_SUFFIX AS "Institutional Suffix",
EN.PRIMARY_RECORD_TYPE_DESC AS "Record Type Descr",

----- CRITERIA INDICATORS
CASE WHEN E.ID_NUMBER IN (
SELECT DISTINCT
T.ID_NUMBER
FROM ADVANCE.SEGMENT T 
WHERE
T.SEGMENT_CODE IN (
'PLAF1'
--'PLAF2'
)) THEN 'Y' ELSE 'N' END AS "Bequest Score - Excellent",

CASE WHEN E.ID_NUMBER IN (
SELECT DISTINCT
PE.ID_NUMBER
FROM PROSPECT P
LEFT OUTER JOIN PROSPECT_ENTITY PE ON P.PROSPECT_ID = PE.PROSPECT_ID
WHERE
P.PG_PROSPECT_IND = 'Y'
) THEN 'Y' ELSE 'N' END AS "Planned Giving Flag",

CASE WHEN E.ID_NUMBER NOT IN (
SELECT DISTINCT
PE.ID_NUMBER
FROM PROSPECT P
LEFT OUTER JOIN PROSPECT_ENTITY PE ON P.PROSPECT_ID = PE.PROSPECT_ID
WHERE
P.PG_PROSPECT_IND = 'Y'
) 
AND
E.ID_NUMBER NOT IN (
SELECT DISTINCT
T.ID_NUMBER
FROM ADVANCE.SEGMENT T 
WHERE
T.SEGMENT_CODE IN (
'PLAF1'
--'PLAF2'
)) THEN 'Y' ELSE 'N' END AS "25+ Gifts",

CASE WHEN PG.ENTITY_ID_NUMBER IS NOT NULL THEN 'Y' ELSE 'N' END AS "Past Planned Giving Donor",

/*CASE WHEN E.ID_NUMBER IN (
SELECT DISTINCT
"ID Number"
FROM FSM_TRANSACTIONS_DM

GROUP BY
"ID Number"

HAVING
COUNT(DISTINCT "Transaction ID") >= 25
) THEN 'Y' ELSE 'N' END AS "25+ Gifts",*/

/*
CASE WHEN ID_NUMBER IN (
SELECT DISTINCT
"ID Number"
FROM FSM_COMMITS
WHERE
"Payment Type Desc" = 'Securities'
) THEN 'Y' ELSE 'N' END AS "Securities Gift",*/

----- ADDRESS BLOCK
ADR."Address Line 1",
ADR."Address Line 2",
ADR."Address Line 3",
ADR."City",
ADR."State",
ADR."ZIP",
CASE WHEN ADR."Country" IS NULL THEN 'United States' ELSE ADR."Country" END AS "Country",
PH."Phone",
EM."Email",

----- BIRTHDATE AND AGE
E.BIRTH_DT AS "Birthdate",
CASE WHEN E.BIRTH_DT NOT LIKE '%00%' THEN TRUNC((SYSDATE - TO_DATE(E.BIRTH_DT, 'YYYYMMDD'))/ 365.25) ELSE 0 END AS "Age",
CASE WHEN E.DEATH_DT = '00000000' THEN 'N' ELSE 'Y' END AS "Deceased",

----- ADDITIONAL CONSTITUENT INFO
FDS.LIFETIME_GIFT_CREDIT_AMOUNT AS "Lifetime Giving",
FDSF.LIFETIME_GIFT_CREDIT_AMOUNT AS "FSM Lifetime Giving",
MAX(RATING.SHORT_DESC) AS "Wealth Rating",
EN.MAJOR_GIFT_PR_TIER AS "Major Gift Tier",
EN.AFFINITY_SCORE AS "Affinity Score",
NVL(SHS.DO_NOT_SOLICIT_FLAG,'N') AS "Do Not Solicit",
NVL(SHS.DO_NOT_MAIL_FLAG,'N') AS "Do Not Mail",
NVL(SHS.DO_NOT_EMAIL_FLAG,'N') AS "Do Not Email",

----- MOST RECENT GIFT INFORMATION
G."Gift Date" AS "Most Recent Gift Date",
G."Gift Amount" AS "Most Recent Gift Amount",
CASE WHEN G."Gift Date" IS NULL THEN NULL ELSE G."Allocation Code" || ' - ' || G."Alloc Short Name" || ' - ' || G."Allocation School" END AS "Most Recent Gift Allocation",

------ MANAGER INFO
MAX(MGR.REPORT_NAME) AS "Manager Name",
MAX(MGR_SPS.REPORT_NAME) AS "Spouse Manager Name",
E.SPOUSE_ID_NUMBER AS "Spouse ID Number",

----- FEINBERG ALUM INFO
FSMDEGREESLIST(E.ID_NUMBER) AS "FSM Degrees List",
COUNT(DISTINCT D.DEGREE_YEAR) AS "Number of Feinberg Degrees",
REPLACE(FSM_PRIORITY_DEGREE_YEAR,'N/A') AS "FSM Priority Degree Year",
REPLACE(FSM_PRIORITY_DEGREE_DESCR,'N/A') AS "FSM Priority Degree Descr",
REPLACE(FSM_PRIORITY_DEGREE_CODE,'N/A') AS "FSM Priority Degree Code",
REPLACE(FSM_PRIORITY_MAJOR_1,'N/A') AS "FSM Priority Major",
REPLACE(FSM_PRIORITY_CONCENTRATION,'N/A') AS "FSM Priority Concentration",

----- LAST CONTACT INFO
CT.CONTACT_DATE AS "Most Recent Contact Date",
CT.CONTACT_TYPE_DESC AS "Most Recent Contact Type",
CT.DESCRIPTION AS "Most Recent Contact Descr",
CT.CONTACT_PURPOSE_DESC AS "Most Recent Contact Purpose",
CT.CONTACTER AS "Most Recent Contacter",

----- CONSTITUENT GROUPS
CASE WHEN E.ID_NUMBER IN (
SELECT DISTINCT
ID_NUMBER
FROM ADVANCE.AFFILIATION
WHERE
AFFIL_LEVEL_CODE = 'CC'
) THEN 'Y' ELSE 'N' END AS "Clinic Client Code",


CASE WHEN E.ID_NUMBER IN (
----- "FEINBERG TEAM" PROSPECT
SELECT DISTINCT
PE.ID_NUMBER
FROM PROSPECT_ENTITY PE
INNER JOIN PROSPECT P ON PE.PROSPECT_ID = P.PROSPECT_ID AND P.PROSPECT_TEAM_CODE = 'FS'
) THEN 'Y' ELSE 'N' END AS "'Feinberg Team' Prospect",


CASE WHEN E.ID_NUMBER IN (
------ FEINBERG DEGREES
SELECT DISTINCT
D.ID_NUMBER
FROM DEGREES D
WHERE
D.SCHOOL_CODE = 'MED'
) THEN 'Y' ELSE 'N' END AS "Feinberg Alum",


CASE WHEN E.ID_NUMBER IN (
----- FEINBERG GIFTS
SELECT DISTINCT
GFT.ID_NUMBER
From nu_gft_trp_gifttrans gft
WHERE
gft.alloc_school = 'FS'

UNION

----- FEINBERG MATCHES
SELECT DISTINCT
MG.match_gift_company_id
From matching_gift mg
WHERE
match_alloc_school = 'FS'

UNION

SELECT DISTINCT
PLG.PLEDGE_DONOR_ID
From pledge PLG
WHERE
pledge_alloc_school = 'FS'
) THEN 'Y' ELSE 'N' END AS "Feinberg Donor",


CASE WHEN E.ID_NUMBER IN (
----- FEINBERG INTEREST AREA
select DISTINCT
ID_NUMBER
from ADVANCE_NU_RPT.INTEREST_AREA_DETAIL
WHERE
INTEREST_AREA = 'Feinberg'
) THEN 'Y' ELSE 'N' END AS "Feinberg Interest Area",

GG."Team" AS "Suggested Team"

FROM FSM_PG_IDS F
INNER JOIN ENTITY E ON F.ID_NUMBER = E.ID_NUMBER
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi EN ON E.ID_NUMBER = EN.ID_NUMBER AND EN.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDS ON E.ID_NUMBER = FDS.ENTITY_KEY AND FDS.ANNUAL_FUND_FLAG = 'N' AND FDS.REPORTING_AREA = 'NA'
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi FDSF ON E.ID_NUMBER = FDSF.ENTITY_KEY AND FDSF.ANNUAL_FUND_FLAG = 'N' AND FDSF.REPORTING_AREA = 'FS'
LEFT OUTER JOIN FSM_ADDRESSES ADR ON E.ID_NUMBER = ADR."ID Number" AND ADR.Rw = 1
LEFT OUTER JOIN FSM_PHONES PH ON E.ID_NUMBER = PH."ID Number" AND PH.Rw = 1
LEFT OUTER JOIN FSM_EMAILS eM ON E.ID_NUMBER = EM."ID Number" AND EM.Rw = 1
----- CONSTITUENT PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE ON E.ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P ON PE.PROSPECT_ID = P.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A ON A.PROSPECT_ID = P.PROSPECT_ID AND A.ACTIVE_IND = 'Y' AND A.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR ON A.ASSIGNMENT_ID_NUMBER = MGR.ID_NUMBER
----- SPOUSE PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE_SPS ON E.SPOUSE_ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P_SPS ON PE_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A_SPS ON A_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID AND A_SPS.ACTIVE_IND = 'Y' AND A_SPS.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR_SPS ON A_SPS.ASSIGNMENT_ID = MGR_SPS.ID_NUMBER
LEFT OUTER JOIN DM_ARD.DIM_DEGREE_SUMMARY@catrackstobi D2 ON E.ID_NUMBER = D2.ID_NUMBER
--LEFT OUTER JOIN FSM_TRANSACTIONS_DM DM ON E.ID_NUMBER = DM."ID Number"

LEFT OUTER JOIN DEGREES D ON E.ID_NUMBER = D.ID_NUMBER AND D.SCHOOL_CODE = 'MED'

----- GIVING INFO
LEFT OUTER JOIN FSM_COMMITS_SEQ G ON E.ID_NUMBER = G."ID Number" AND G.Rw = 1

----- RATINGS
LEFT OUTER JOIN EVALUATION EV ON E.ID_NUMBER = EV.ID_NUMBER
LEFT OUTER JOIN TMS_RATING RATING ON EV.RATING_CODE = RATING.rating_code

----- MOST RECENT CONTACT INFO
LEFT OUTER JOIN FSM_CONTACT_REPORTS CT ON E.ID_NUMBER = CT.ID_NUMBER AND CT.RW = 1
LEFT OUTER JOIN DM_ARD.DIM_SPECIAL_HANDLING_SUMMARY@catrackstobi SHS ON E.ID_NUMBER = SHS.ID_NUMBER

LEFT OUTER JOIN (
SELECT DISTINCT 
F."ID Number",
A."Team 1" AS "Team",
SUM(F."New Gifts and Commitments") AS "Amount",
ROW_NUMBER() OVER (PARTITION BY F."ID Number" ORDER BY SUM(F."New Gifts and Commitments") DESC) AS RW

FROM FSM_TRANSACTIONS_DM F
INNER JOIN FSM_ALLOCATIONS A ON F."Allocation Code" = A."Allocation Code"

WHERE
F."New Gifts and Commitments" > 0

GROUP BY
F."ID Number",
A."Team 1"
) GG ON E.ID_NUMBER = GG."ID Number" AND GG.RW = 1

LEFT OUTER JOIN (
SELECT DISTINCT
G.ENTITY_ID_NUMBER
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID

WHERE
CASE
WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC
WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC
ELSE T.TRANSACTION_TYPE_DESC END IN ('Bequest Expectancy','Bequest Received','Charitable Remainder Annuity Trusts','Charitable Remainder Unitrusts','Gift Annuities','Lead Trust','Life Insurance Received')
) PG ON E.ID_NUMBER = PG.ENTITY_ID_NUMBER

WHERE
CASE WHEN E.DEATH_DT = '00000000' THEN 'N' ELSE 'Y' END = 'N'
AND
(
FSM_PRIORITY_DEGREE_YEAR IS NULL 
OR 
FSM_PRIORITY_DEGREE_YEAR IN ('',' ','N/A') 
OR 
EXTRACT(YEAR FROM SYSDATE) - REPLACE(REPLACE(FSM_PRIORITY_DEGREE_YEAR,'N/A',''),' ','') <= 75
)
--AND
--E.LAST_NAME NOT IN ('',' ')

GROUP BY
E.ID_NUMBER,
E.REPORT_NAME,
E.LAST_NAME,
E.FIRST_NAME,
E.INSTITUTIONAL_SUFFIX,

ADR."Address Line 1",
ADR."Address Line 2",
ADR."Address Line 3",
ADR."City",
ADR."State",
ADR."ZIP",
ADR."Country",
PH."Phone",
EM."Email",

E.BIRTH_DT,

D.ID_NUMBER,

G."Gift Date",
G."Gift Amount",
G."Allocation Code" || ' - ' || G."Alloc Short Name" || ' - ' || G."Allocation School",

E.DEATH_DT,

E.SPOUSE_ID_NUMBER,

CT.CONTACT_DATE,
CT.CONTACT_TYPE_DESC,
CT.DESCRIPTION,
CT.CONTACT_PURPOSE_DESC,
CT.CONTACTER,

FDS.LIFETIME_GIFT_CREDIT_AMOUNT,
FDSF.LIFETIME_GIFT_CREDIT_AMOUNT,
EN.MAJOR_GIFT_PR_TIER,
EN.AFFINITY_SCORE,
NVL(SHS.DO_NOT_SOLICIT_FLAG,'N'),
NVL(SHS.DO_NOT_MAIL_FLAG,'N'),
NVL(SHS.DO_NOT_EMAIL_FLAG,'N'),
EN.PREF_CLASS_YEAR,
EN.PREF_SCHOOL_CODE,
EN.PREF_SCHOOL_NAME,
FSM_PRIORITY_DEGREE_YEAR,
FSM_PRIORITY_DEGREE_DESCR,
FSM_PRIORITY_DEGREE_CODE,
FSM_PRIORITY_MAJOR_1,
FSM_PRIORITY_CONCENTRATION,
GG."Team",
EN.PRIMARY_RECORD_TYPE_DESC,
PG.ENTITY_ID_NUMBER;
