SELECT DISTINCT
E.ID_NUMBER AS "ID Number",
E.FIRST_NAME AS "First Name",
E.LAST_NAME AS "Last Name",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
E.EMAIL_ADDRESS AS "Email",
--G.TRANS_ID_NUMBER AS "Transaction ID",
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Date(mmddyyyy)",
SUM(G.NEW_GIFTS_AND_CMIT_AMT) AS "New Gifts and Commitments",
SUM(G.PLEDGE_PAYMENT_AMOUNT) AS "Pledge Payment Amount",
SUM(NVL(P.PLEDGE_BALANCE,CAST(0.00 AS NUMBER))) AS "Pledge Balance Amount",
SUM(G.GIFT_CREDIT_AMOUNT) AS "Gift Soft Credit Amount",

E2.ID_NUMBER AS "GS ID Number",
E2.FIRST_NAME AS "GS First Name",
E2.LAST_NAME AS "GS Last Name",
E2.PREF_MAIL_NAME AS "GS Preferred Mail Name",
E2.EMAIL_ADDRESS AS "GS Email",

AL.ALLOCATION_CODE AS "Allocation Code",
AL.ALLOC_SHORT_NAME AS "Allocation Short Name",

A.APPEAL_CODE AS "Appeal Code",
A.DESCRIPTION AS "Appeal",

AF.CLINIC_CLIENT_AFFIL_FLAG AS "Clinic Client Affiliation Flag",
AF.CURRENT_FACULTY_AFFIL_FLAG AS "Faculty Affiliation Flag",
E.RECORD_STATUS_DESC AS "Record Status",
AN.ANONYMOUS_LEVEL_DESC AS "Anonymous Level"

FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON G.ENTITY_ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
LEFT OUTER JOIN DM_ARD.DIM_GIFT_ASSOCIATION@catrackstobi GA ON G.GIFT_ASSOCIATED_SID = GA.GIFT_ASSOCIATED_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi P ON G.PRIMARY_PLEDGE_SID = P.PRIMARY_PLEDGE_SID AND
      CASE
      WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC
      WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC
      ELSE T.TRANSACTION_TYPE_DESC END IN ('Non Binding Intent','Bequest Expectancy','Straight Pledge','Telefund Pledge','Recurring Pledge','Grant Pledge')
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.TRANS_ID_NUMBER = G2.TRANS_ID_NUMBER AND G.DATE_OF_RECORD_KEY = G2.DATE_OF_RECORD_KEY AND G.GIFT_ASSOCIATED_SID IN ('101','2','105') AND G2.GIFT_ASSOCIATED_SID NOT IN ('101','2','105')
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E2 ON G2.ENTITY_ID_NUMBER = E2.ID_NUMBER AND E2.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_AFFILIATION_SUMMARY@catrackstobi AF ON E.ID_NUMBER = AF.ENTITY_KEY
LEFT OUTER JOIN DM_ARD.DIM_ANONYMOUS_LEVEL@catrackstobi AN ON G.ANONYMOUS_LEVEL_SID = AN.ANONYMOUS_LEVEL_SID

WHERE
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
GA.GIFT_ASSOCIATED_CODE NOT IN (/*'C',*/'H','M') -- EXCLUDE SOFT CREDITS, IMO, IHO
AND
AL.ALLOCATION_CODE IN ('3203005750301GFT')
AND (
G.GIFT_CREDIT_AMOUNT > 0
OR
G.PLEDGE_CREDIT_AMOUNT > 0
)

GROUP BY
E.ID_NUMBER,
E.FIRST_NAME,
E.LAST_NAME,
E.PREF_MAIL_NAME,
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD'),

AL.ALLOCATION_CODE,
AL.ALLOC_SHORT_NAME,

A.APPEAL_CODE,
A.DESCRIPTION,

E2.ID_NUMBER,
E2.FIRST_NAME,
E2.LAST_NAME,
E2.PREF_MAIL_NAME,

E.EMAIL_ADDRESS,
E2.EMAIL_ADDRESS,

AF.CLINIC_CLIENT_AFFIL_FLAG,
AF.CURRENT_FACULTY_AFFIL_FLAG,
E.RECORD_STATUS_DESC,
AN.ANONYMOUS_LEVEL_DESC

