CREATE OR REPLACE VIEW RPT_RVA7647.FSM_EMAILS AS

SELECT
E.ID_NUMBER AS "ID Number",
EMAIL_ADDRESS AS "Email",
E.EMAIL_TYPE_CODE AS "Email Type Code",
ET.SHORT_DESC AS "Email Type Desc",
E.EMAIL_STATUS_CODE AS "Email Status Code",
ES.SHORT_DESC AS "Email Status Desc",
E.PREFERRED_IND AS "Preferred",
E.START_DT AS "Start Date",
ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY CASE WHEN E.PREFERRED_IND = 'Y' THEN 1 WHEN E.EMAIL_TYPE_CODE = 'X' THEN 2 WHEN E.EMAIL_TYPE_CODE = 'Y' THEN 3 ELSE 4 END) AS Rw
FROM ADVANCE.EMAIL E 
LEFT OUTER JOIN ADVANCE.TMS_EMAIL_TYPE ET ON E.EMAIL_TYPE_CODE = ET.email_type_code
LEFT OUTER JOIN ADVANCE.TMS_EMAIL_STATUS ES ON E.EMAIL_STATUS_CODE = ES.email_status_code
WHERE
E.EMAIL_STATUS_CODE = 'A'
;
