CREATE OR REPLACE VIEW RPT_RVA7647.FSM_PG_IDS AS

SELECT DISTINCT
ID_NUMBER

FROM FSM_IDS
WHERE ID_NUMBER IN (

---"EXCELLENT" BEQUEST SCORE
SELECT DISTINCT
T.ID_NUMBER
FROM ADVANCE.SEGMENT T 
WHERE
T.SEGMENT_CODE IN (
'PLAF1'
--'PLAF2'
)

UNION

---- "PLANNED GIVING" PROSPECT
SELECT DISTINCT
PE.ID_NUMBER
FROM PROSPECT P
LEFT OUTER JOIN PROSPECT_ENTITY PE ON P.PROSPECT_ID = PE.PROSPECT_ID
WHERE
P.PG_PROSPECT_IND = 'Y'

UNION

----- 25 GIFTS OR MORE
SELECT DISTINCT
"ID Number"
FROM FSM_TRANSACTIONS_DM

GROUP BY
"ID Number"

HAVING
COUNT(DISTINCT "Transaction ID") >= 25

/*UNION

----- SECURITIES GIFT
SELECT DISTINCT
"ID Number"
FROM FSM_COMMITS
WHERE
"Payment Type Desc" = 'Securities'*/

)
