CREATE OR REPLACE VIEW fsm_demographic AS

SELECT
E.ID_NUMBER,
E.PREF_MAIL_NAME as "Prospect Name",
E.LAST_NAME AS "Last Name",
E.FIRST_NAME AS "First Name",
E.INSTITUTIONAL_SUFFIX AS "Institutional Suffix",

----- ADDRESS BLOCK
ADR."Address Line 1",
ADR."Address Line 2",
ADR."Address Line 3",
ADR."City",
ADR."State",
ADR."ZIP",
ADR."Country",
PH."Phone",
EM."Email",

----- BIRTHDATE AND AGE
E.BIRTH_DT AS "Birthdate",
CASE WHEN E.BIRTH_DT <> '00000000' THEN TRUNC((SYSDATE - TO_DATE(E.BIRTH_DT, 'YYYY-MM-DD'))/ 365.25) ELSE 0 END AS "Age",

----- RATINGS
RATING.SHORT_DESC AS "Wealth Rating",
--AQ.prospect_affinity_letter AS "Affinity Grade",
LG.LIFETIME_GIVING AS "NU Lifetime Giving",
rpt_rva7647.fsm_lifetime_giving(E.ID_NUMBER) AS "FSM Lifetime Giving",
IAS.potential_interest_areas AS "Potential Interest Areas",
IAS.multi_or_single_interest AS "Multi or Single Interest",

----- MOST RECENT GIFT INFORMATION
G."Gift Date" AS "Most Recent Gift Date",
G."Gift Amount" AS "Most Recent Gift Amount",
CASE WHEN G."Gift Date" IS NULL THEN NULL ELSE G."Allocation Code" || ' - ' || G."Alloc Short Name" || ' - ' || G."Allocation School" END AS "Most Recent Gift Allocation",

----- CONSECUTIVE YEARS GIVING
GC.GIFT_CLUB_REASON AS "NU Consecutive Giving Years",
FCG.ConsecutiveGivingYears AS "FSM Consecutive Giving Years",

----- PROSPECT INFORMATION
P.PROSPECT_ID,
P.ACTIVE_IND AS "Prospect Active Indicator",
STAGE.short_desc AS "Prospect Stage",
/*
----- ASSIGNMENT HISTORY
CASE WHEN E.ID_NUMBER IN (SELECT ID_NUMBER from ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY t WHERE T.ASSIGNMENT_ACTIVE_IND = 'Y' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Currently Assigned",
*/
MGR.REPORT_NAME AS "Manager Name",

/*
CASE WHEN E.ID_NUMBER IN (SELECT ID_NUMBER FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ASSIGNMENT_ACTIVE_IND = 'N' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Previously Assigned",
(SELECT max(ASSIGNMENT_REPORT_NAME) FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ID_NUMBER = E.ID_NUMBER AND T.STOP_DATE = (SELECT MAX(CASE WHEN T.ASSIGNMENT_ACTIVE_IND = 'Y' THEN START_DATE ELSE STOP_DATE END) FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ID_NUMBER = E.ID_NUMBER AND T.ASSIGNMENT_TYPE = 'PM')) AS "Most Recent Manager",

----- SPOUSE ASSIGNMENT HISTORY
CASE WHEN E.SPOUSE_ID_NUMBER IN (SELECT ID_NUMBER from ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY t WHERE T.ASSIGNMENT_ACTIVE_IND = 'Y' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Spouse Currently Assigned",
*/
MGR_SPS.REPORT_NAME AS "Spouse Manager Name",
/*
CASE WHEN E.SPOUSE_ID_NUMBER IN (SELECT ID_NUMBER FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ASSIGNMENT_ACTIVE_IND = 'N' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Spouse Previously Assigned",
*/
----- FEINBERG ALUM INFO
CASE WHEN D.ID_NUMBER IS NOT NULL THEN 'Y' ELSE 'N' END AS "Feinberg Alum",
FSMDEGREESLIST(E.ID_NUMBER) AS "FSM Degrees List",
COUNT(DISTINCT D.DEGREE_YEAR) AS "Number of Feinberg Degrees",
CASE WHEN D1."Financial Aid Desc" LIKE '%RECEIVED%' OR D2."Financial Aid Desc" LIKE '%RECEIVED%' OR D3."Financial Aid Desc" LIKE '%RECEIVED%' THEN 'Y' ELSE NULL END AS "Received Financial Aid",

----- DEGREE 1 INFO
D1.DEGREE_YEAR AS "Degree 1 Year",
D1."Degree Code Desc" AS "Degree 1 Type",
D1."Degree Level Desc" AS "Degree 1 Level",
D1."Department Desc" AS "Degree 1 Department",
D1."Concentration Desc" AS "Degree 1 Concentration",

----- DEGREE 2 INFO
D2.DEGREE_YEAR AS "Degree 2 Year",
D2."Degree Code Desc" AS "Degree 2 Type",
D2."Degree Level Desc" AS "Degree 2 Level",
D2."Department Desc" AS "Degree 2 Department",
D2."Concentration Desc" AS "Degree 2 Concentration",

----- DEGREE 3 INFO
D3.DEGREE_YEAR AS "Degree 3 Year",
D3."Degree Code Desc" AS "Degree 3 Type",
D3."Degree Level Desc" AS "Degree 3 Level",
D3."Department Desc" AS "Degree 3 Department",
D3."Concentration Desc" AS "Degree 3 Concentration",

----- CONTACT INFO
COUNT(DISTINCT C.REPORT_ID) AS "Number of Contact Reports",
CT.CONTACT_DATE AS "Most Recent Contact Date",
CT.CONTACT_TYPE_DESC AS "Most Recent Contact Type",
CT.DESCRIPTION AS "Most Recent Contact Descr",
CT.CONTACT_PURPOSE_DESC AS "Most Recent Contact Purpose",
CT.CONTACTER AS "Most Recent Contacter",
CASE WHEN CT.CONTACT_DATE >= SYSDATE - 90 THEN 'Y' ELSE 'N' END AS "Contacted Within Last 90",

----- EVENT INFO
COUNT(DISTINCT EP.EVENT_ID) AS "Number of Events Attended",
EVT.EVENT_START_DATETIME AS "Most Recent Event Date",
EVT.EVENT_NAME AS "Most Recent Event Name",
EVT.Event_Type AS "Most Recent Event Type",

----- SPECIAL HANDLING
CASE WHEN E.ID_NUMBER IN (SELECT H.ID_NUMBER FROM HANDLING H WHERE H.HND_TYPE_CODE = 'NC' AND h.hnd_status_code = 'A') THEN 'Y' ELSE 'N' END AS "No Contact",
CASE WHEN E.ID_NUMBER IN (SELECT H.ID_NUMBER FROM HANDLING H WHERE H.HND_TYPE_CODE = 'DNS' AND h.hnd_status_code = 'A') THEN 'Y' ELSE 'N' END AS "No Solicit",

----- CLINIC CLIENT CODE (GRATEFUL PATIENT)
CASE WHEN E.ID_NUMBER IN (select DISTINCT ID_NUMBER from ADVANCE.AFFILIATION t WHERE AFFIL_LEVEL_CODE = 'CC' AND AFFIL_STATUS_CODE = 'C') THEN 'Y' ELSE 'N' END AS "Clinic Client Code"

FROM FSM_IDS F
INNER JOIN ENTITY E ON F.ID_NUMBER = E.ID_NUMBER
LEFT OUTER JOIN FSM_ADDRESSES ADR ON E.ID_NUMBER = ADR."ID Number" AND ADR.Rw = 1
LEFT OUTER JOIN FSM_PHONES PH ON E.ID_NUMBER = PH."ID Number" AND PH.Rw = 1
LEFT OUTER JOIN FSM_EMAILS eM ON E.ID_NUMBER = EM."ID Number" AND EM.Rw = 1
----- CONSTITUENT PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE ON E.ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P ON PE.PROSPECT_ID = P.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A ON A.PROSPECT_ID = P.PROSPECT_ID AND A.ACTIVE_IND = 'Y' AND A.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR ON A.ASSIGNMENT_ID = MGR.ID_NUMBER
LEFT OUTER JOIN TMS_STAGE STAGE ON P.STAGE_CODE = STAGE.STAGE_code
----- SPOUSE PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE_SPS ON E.SPOUSE_ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P_SPS ON PE_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A_SPS ON A_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID AND A_SPS.ACTIVE_IND = 'Y' AND A_SPS.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR_SPS ON A_SPS.ASSIGNMENT_ID = MGR_SPS.ID_NUMBER

LEFT OUTER JOIN DEGREES D ON E.ID_NUMBER = D.ID_NUMBER AND D.SCHOOL_CODE = 'MED'
LEFT OUTER JOIN CONTACT_REPORT C ON E.ID_NUMBER = C.ID_NUMBER
LEFT OUTER JOIN EP_PARTICIPANT EP ON E.ID_NUMBER = EP.ID_NUMBER

----- MOST RECENT CONTACT INFO
LEFT OUTER JOIN FSM_CONTACT_REPORTS CT ON E.ID_NUMBER = CT.ID_NUMBER AND CT.RW = 1

----- MOST RECENT EVENT INFO
LEFT OUTER JOIN FSM_EVENTS EVT ON E.ID_NUMBER = EVT.ID_NUMBER AND EVT.Rw = 1

----- DEGREE 1 INFO
LEFT OUTER JOIN FSM_DEGREES D1 ON E.ID_NUMBER = D1.ID_NUMBER AND D1.Rw = 1

----- DEGREE 2 INFO
LEFT OUTER JOIN FSM_DEGREES D2 ON E.ID_NUMBER = D2.ID_NUMBER AND D2.Rw = 2

----- DEGREE 3 INFO
LEFT OUTER JOIN FSM_DEGREES D3 ON E.ID_NUMBER = D3.ID_NUMBER AND D3.Rw = 3

----- GIVING INFO
LEFT OUTER JOIN FSM_COMMITS_SEQ G ON E.ID_NUMBER = G."ID Number" AND G.Rw = 1
LEFT OUTER JOIN GIFT_CLUBS GC ON E.ID_NUMBER  = GC.GIFT_CLUB_ID_NUMBER AND GIFT_CLUB_STATUS = 'A' AND GIFT_CLUB_CODE = 'NUL'
LEFT OUTER JOIN FSM_CONSECUTIVE_GIVING_YEARS FCG ON E.ID_NUMBER = FCG.ConsecutiveGivingYears

----- RATINGS
LEFT OUTER JOIN EVALUATION EV ON E.ID_NUMBER = EV.ID_NUMBER
LEFT OUTER JOIN TMS_RATING RATING ON EV.RATING_CODE = RATING.rating_code
LEFT OUTER JOIN advance_nu_rpt.entity_interest_area_summary IAS ON E.ID_NUMBER = IAS.id_number
--LEFT OUTER JOIN RPT_BRJ8948.AFFINITY_QUAL AQ ON E.ID_NUMBER = AQ.PRIMARY_ENTITY_ID
LEFT OUTER JOIN nu_rpt_t_lifetime_giving LG ON E.ID_NUMBER = LG.ID_NUMBER

WHERE
E.DEATH_DT = '00000000'

GROUP BY
E.ID_NUMBER,
E.PREF_MAIL_NAME,
E.LAST_NAME,
E.FIRST_NAME,
RATING.SHORT_DESC,
E.INSTITUTIONAL_SUFFIX,
P.PROSPECT_ID,
MGR.REPORT_NAME,
P.ACTIVE_IND,
STAGE.short_desc,
--AFFINITY_SCORE,

ADR."Address Line 1",
ADR."Address Line 2",
ADR."Address Line 3",
ADR."City",
ADR."State",
ADR."ZIP",
ADR."Country",
PH."Phone",
EM."Email",

E.BIRTH_DT,

MGR_SPS.REPORT_NAME,
D.ID_NUMBER,
D1.DEGREE_YEAR,
D1."Degree Code Desc",
D1."Degree Level Desc",
D1."Department Desc",
D1."Concentration Desc",

D2.DEGREE_YEAR,
D2."Degree Code Desc",
D2."Degree Level Desc",
D2."Department Desc",
D2."Concentration Desc",

D3.DEGREE_YEAR,
D3."Degree Code Desc",
D3."Degree Level Desc",
D3."Department Desc",
D3."Concentration Desc",
CASE WHEN D1."Financial Aid Desc" LIKE '%RECEIVED%' OR D2."Financial Aid Desc" LIKE '%RECEIVED%' OR D3."Financial Aid Desc" LIKE '%RECEIVED%' THEN 'Y' ELSE NULL END,
  
EVT.EVENT_START_DATETIME,
EVT.EVENT_NAME,
EVT.Event_Type,

CT.CONTACT_DATE,
CT.CONTACT_TYPE_DESC,
CT.DESCRIPTION,
CT.CONTACT_PURPOSE_DESC,
CT.CONTACTER,

G."Gift Date",
G."Gift Amount",
G."Allocation Code" || ' - ' || G."Alloc Short Name" || ' - ' || G."Allocation School",

E.ID_NUMBER,
E.SPOUSE_ID_NUMBER,

GC.GIFT_CLUB_REASON,
FCG.ConsecutiveGivingYears,
IAS.potential_interest_areas,
IAS.multi_or_single_interest,
LG.LIFETIME_GIVING
--AQ.prospect_affinity_letter;
