CREATE OR REPLACE VIEW RPT_RVA7647.FSM_DEGREES AS

SELECT
ID_NUMBER,
D.DEGREE_YEAR,
S.long_desc AS "School Description",
DT.full_desc AS "Degree Type Description",
DP.full_desc AS "Department Desc",
DV.FULL_desc AS "Division Desc",
M.FULL_DESC AS "Major Desc",
DC.FULL_DESC AS "Concentration Desc",
FA.SHORT_DESC AS "Financial Aid Desc",
DL.short_desc AS "Degree Level Desc",
C.short_desc AS "Campus Desc",
DC2.FULL_DESC AS "Degree Code Desc",
ROW_NUMBER() OVER (PARTITION BY D.ID_NUMBER ORDER BY D.DEGREE_YEAR) AS Rw
FROM DEGREES D
LEFT OUTER JOIN ADVANCE.TMS_SCHOOL S ON D.SCHOOL_CODE = S.SCHOOL_CODE
LEFT OUTER JOIN ADVANCE.TMS_DEGREE_TYPE DT ON D.DEGREE_TYPE = DT.degree_type_code
LEFT OUTER JOIN ADVANCE.TMS_CONCENTRATION DC ON D.CONCENTRATION_CODE = DC.CONCENTRATION_CODE
LEFT OUTER JOIN ADVANCE.TMS_DEGREE_LEVEL DL ON D.DEGREE_LEVEL_CODE = DL.DEGREE_LEVEL_CODE
LEFT OUTER JOIN ADVANCE.TMS_DEGREES DC2 ON D.DEGREE_CODE = DC2.DEGREE_CODE
LEFT OUTER JOIN ADVANCE.TMS_CAMPUS C ON D.CAMPUS_CODE = C.CAMPUS_CODE
LEFT OUTER JOIN ADVANCE.TMS_FINANCIAL_AID FA ON D.FINANCIAL_AID_CODE = FA.FINANCIAL_AID_CODE
LEFT OUTER JOIN ADVANCE.TMS_MAJORS M ON D.MAJOR_CODE1 = M.MAJOR_CODE
LEFT OUTER JOIN ADVANCE.TMS_DIVISION DV ON D.DIVISION_CODE = DV.DIVISION_CODE
LEFT OUTER JOIN ADVANCE.TMS_DEPT_CODE DP ON D.DEPT_CODE = DP.DEPT_CODE
WHERE
D.SCHOOL_CODE = 'MED'
;
