CREATE OR REPLACE VIEW RPT_RVA7647.FSM_ADDRESSES AS

SELECT
A.ID_NUMBER AS "ID Number",
A.COMPANY_NAME_1 AS "Company Name",
STREET1 AS "Address Line 1",
STREET2 AS "Address Line 2",
STREET3 AS "Address Line 3",
CITY AS "City",
A.STATE_CODE AS "State",
ZIPCODE AS "ZIP",
C.SHORT_DESC AS "Country",
A.ADDR_PREF_IND AS "Preferred",
A.ADDR_TYPE_CODE AS "Addr Type Code",
AT.LONG_DESC AS "Addr Type Desc",
A.ADDR_SRC_CODE AS "Addr Src Code",
SRC.SHORT_DESC AS "Addr Src Desc",
A.ADDR_STATUS_CODE AS "Addr Status Code",
S.SHORT_DESC AS "Addr Status Desc",
A.ADDRESS_CODE AS "Addr Code",
AC.SHORT_DESC AS "Addr Code Desc",
A.START_DT AS "Start Date",
ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY CASE WHEN A.ADDR_PREF_IND = 'Y' THEN 1 WHEN S.hierarchy_order = 0 THEN 1000 ELSE S.hierarchy_order END) AS Rw
FROM ADVANCE.ADDRESS A
LEFT OUTER JOIN TMS_ADDRESS_TYPE AT ON A.ADDR_TYPE_CODE = AT.ADDR_TYPE_CODE
LEFT OUTER JOIN TMS_ADDR_STATUS S ON A.ADDR_STATUS_CODE = S.ADDR_STATUS_CODE
LEFT OUTER JOIN TMS_ADDR_SRC SRC ON A.ADDR_SRC_CODE = SRC.ADDR_SRC_CODE
LEFT OUTER JOIN TMS_ADDRESS_CODE AC ON A.ADDRESS_CODE = AC.ADDRESS_CODE
LEFT OUTER JOIN TMS_COUNTRY C ON A.COUNTRY_CODE = C.COUNTRY_CODE

WHERE
A.ADDR_STATUS_CODE = 'A'
;
