create or replace view fsm_demographic as

SELECT
E.ID_NUMBER,
E.PREF_MAIL_NAME as "Prospect Name",
E.LAST_NAME AS "Last Name",
E.FIRST_NAME AS "First Name",
--RATING.SHORT_DESC AS "Rating",
--QUALIFICATION_DESC AS "Qualification Wealth Eval",
E.INSTITUTIONAL_SUFFIX AS "Institutional Suffix",

----- ADDRESS BLOCK
ADR.STREET1 AS "Address Line 1",
ADR.STREET2 AS "Address Line 2",
ADR.STREET3 AS "Address Line 3",
ADR.CITY AS "City",
ADR.STATE_CODE AS "State",
ADR.ZIPCODE AS "ZIP",
ADR.COUNTRY_CODE AS "Country",

----- BIRTHDATE AND AGE
E.BIRTH_DT AS "Birthdate",
--CASE WHEN E.BIRTH_DT = '00000000' THEN '0' 

LIFETIME_NEWGIFT_CMIT AS "Lifetime Giving",
AFFINITY_SCORE AS "Affinity Score",

----- MOST RECENT GIFT INFORMATION
G.DATE_OF_RECORD AS "Most Recent Gift Date",
G.CREDIT_AMOUNT AS "Most Recent Gift Amount",
G.ALLOCATION_CODE || ' - ' || G.ALLOC_SHORT_NAME || ' - ' || G."Allocation School" AS "Most Recent Gift Allocation",

----- CONSECUTIVE YEARS GIVING
GC.GIFT_CLUB_REASON AS "Consecutive Giving Years",

----- PROSPECT INFORMATION
P.PROSPECT_ID,
P.ACTIVE_IND AS "Prospect Active Indicator",
STAGE.short_desc AS "Prospect Stage",
/*
----- ASSIGNMENT HISTORY
CASE WHEN E.ID_NUMBER IN (SELECT ID_NUMBER from ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY t WHERE T.ASSIGNMENT_ACTIVE_IND = 'Y' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Currently Assigned",
*/
MGR.REPORT_NAME AS "Manager Name",

/*
CASE WHEN E.ID_NUMBER IN (SELECT ID_NUMBER FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ASSIGNMENT_ACTIVE_IND = 'N' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Previously Assigned",
(SELECT max(ASSIGNMENT_REPORT_NAME) FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ID_NUMBER = E.ID_NUMBER AND T.STOP_DATE = (SELECT MAX(CASE WHEN T.ASSIGNMENT_ACTIVE_IND = 'Y' THEN START_DATE ELSE STOP_DATE END) FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ID_NUMBER = E.ID_NUMBER AND T.ASSIGNMENT_TYPE = 'PM')) AS "Most Recent Manager",

----- SPOUSE ASSIGNMENT HISTORY
CASE WHEN E.SPOUSE_ID_NUMBER IN (SELECT ID_NUMBER from ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY t WHERE T.ASSIGNMENT_ACTIVE_IND = 'Y' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Spouse Currently Assigned",
*/
MGR_SPS.REPORT_NAME AS "Spouse Manager Name",
/*
CASE WHEN E.SPOUSE_ID_NUMBER IN (SELECT ID_NUMBER FROM ADVANCE_NU_RPT.V_ASSIGNMENT_HISTORY T WHERE T.ASSIGNMENT_ACTIVE_IND = 'N' AND T.ASSIGNMENT_TYPE = 'PM') THEN 'Y' ELSE 'N' END AS "Spouse Previously Assigned",
*/
----- FEINBERG ALUM INFO
CASE WHEN D.ID_NUMBER IS NOT NULL THEN 'Y' ELSE 'N' END AS "Feinberg Alum",
COUNT(DISTINCT D.DEGREE_YEAR) AS "Number of Feinberg Degrees",
CASE WHEN D1."Financial Aid Desc" LIKE '%RECEIVED%' OR D2."Financial Aid Desc" LIKE '%RECEIVED%' OR D3."Financial Aid Desc" LIKE '%RECEIVED%' THEN 'Y' ELSE NULL END AS "Received Financial Aid",

----- DEGREE 1 INFO
D1.DEGREE_YEAR AS "Degree 1 Year",
D1."Degree Code Desc" AS "Degree 1 Type",
D1."Degree Level Desc" AS "Degree 1 Level",
D1."Department Desc" AS "Degree 1 Department",
D1."Concentration Desc" AS "Degree 1 Concentration",

----- DEGREE 2 INFO
D2.DEGREE_YEAR AS "Degree 2 Year",
D2."Degree Code Desc" AS "Degree 2 Type",
D2."Degree Level Desc" AS "Degree 2 Level",
D2."Department Desc" AS "Degree 2 Department",
D2."Concentration Desc" AS "Degree 2 Concentration",

----- DEGREE 3 INFO
D3.DEGREE_YEAR AS "Degree 3 Year",
D3."Degree Code Desc" AS "Degree 3 Type",
D3."Degree Level Desc" AS "Degree 3 Level",
D3."Department Desc" AS "Degree 3 Department",
D3."Concentration Desc" AS "Degree 3 Concentration",

----- CONTACT INFO
COUNT(DISTINCT C.REPORT_ID) AS "Number of Contact Reports",
CT.CONTACT_DATE AS "Most Recent Contact Date",
CT.CONTACT_TYPE_DESC AS "Most Recent Contact Type",
CT.DESCRIPTION AS "Most Recent Contact Descr",
CT.CONTACT_PURPOSE_DESC AS "Most Recent Contact Purpose",
CT.CONTACTER AS "Most Recent Contacter",
CASE WHEN CT.CONTACT_DATE >= SYSDATE - 90 THEN 'Y' ELSE 'N' END AS "Contacted Within Last 90",

----- EVENT INFO
COUNT(DISTINCT EP.EVENT_ID) AS "Number of Events Attended",
EVT.EVENT_START_DATETIME AS "Most Recent Event Date",
EVT.EVENT_NAME AS "Most Recent Event Name",
EVT.Event_Type AS "Most Recent Event Type",

----- SPECIAL HANDLING
CASE WHEN E.ID_NUMBER IN (SELECT H.ID_NUMBER FROM HANDLING H WHERE H.HND_TYPE_CODE = 'NC' AND h.hnd_status_code = 'A') THEN 'Y' ELSE 'N' END AS "No Contact",
CASE WHEN E.ID_NUMBER IN (SELECT H.ID_NUMBER FROM HANDLING H WHERE H.HND_TYPE_CODE = 'DNS' AND h.hnd_status_code = 'A') THEN 'Y' ELSE 'N' END AS "No Solicit",

----- CLINIC CLIENT CODE (GRATEFUL PATIENT)
CASE WHEN E.ID_NUMBER IN (select DISTINCT ID_NUMBER from ADVANCE.AFFILIATION t WHERE AFFIL_LEVEL_CODE = 'CC' AND AFFIL_STATUS_CODE = 'C') THEN 'Y' ELSE 'N' END AS "Clinic Client Code"

FROM ENTITY E
LEFT OUTER JOIN ADDRESS ADR ON E.ID_NUMBER = ADR.ID_NUMBER AND ADR.ADDR_STATUS_CODE = 'A' AND ADR.ADDR_TYPE_CODE = 'H'
----- CONSTITUENT PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE ON E.ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P ON PE.PROSPECT_ID = P.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A ON A.PROSPECT_ID = P.PROSPECT_ID AND A.ACTIVE_IND = 'Y' AND A.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR ON A.ASSIGNMENT_ID = MGR.ID_NUMBER
LEFT OUTER JOIN TMS_STAGE STAGE ON P.STAGE_CODE = STAGE.STAGE_code
----- SPOUSE PROSPECT AND ASSIGNMENT INFO
LEFT OUTER JOIN PROSPECT_ENTITY PE_SPS ON E.SPOUSE_ID_NUMBER = PE.ID_NUMBER
LEFT OUTER JOIN PROSPECT P_SPS ON PE_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID
LEFT OUTER JOIN ASSIGNMENT A_SPS ON A_SPS.PROSPECT_ID = P_SPS.PROSPECT_ID AND A_SPS.ACTIVE_IND = 'Y' AND A_SPS.ASSIGNMENT_TYPE = 'PM'
LEFT OUTER JOIN ENTITY MGR_SPS ON A_SPS.ASSIGNMENT_ID = MGR_SPS.ID_NUMBER

LEFT OUTER JOIN DEGREES D ON E.ID_NUMBER = D.ID_NUMBER AND D.SCHOOL_CODE = 'MED'
LEFT OUTER JOIN CONTACT_REPORT C ON E.ID_NUMBER = C.ID_NUMBER
LEFT OUTER JOIN EP_PARTICIPANT EP ON E.ID_NUMBER = EP.ID_NUMBER

----- MOST RECENT CONTACT INFO
LEFT OUTER JOIN FSM_CONTACT_REPORTS CT ON E.ID_NUMBER = CT.ID_NUMBER AND CT.RW = 1

----- MOST RECENT EVENT INFO
LEFT OUTER JOIN FSM_EVENTS EVT ON E.ID_NUMBER = EVT.ID_NUMBER AND EVT.Rw = 1

----- DEGREE 1 INFO
LEFT OUTER JOIN FSM_DEGREES D1 ON E.ID_NUMBER = D1.ID_NUMBER AND D1.Rw = 1

----- DEGREE 2 INFO
LEFT OUTER JOIN FSM_DEGREES D2 ON E.ID_NUMBER = D2.ID_NUMBER AND D2.Rw = 2

----- DEGREE 3 INFO
LEFT OUTER JOIN FSM_DEGREES D3 ON E.ID_NUMBER = D3.ID_NUMBER AND D3.Rw = 3

----- GIVING INFO
LEFT OUTER JOIN FSM_COMMITS_SEQ G ON E.ID_NUMBER = G.ID_NUMBER AND G.Rw = 1
 
LEFT OUTER JOIN GIFT_CLUBS GC ON E.ID_NUMBER  = GC.GIFT_CLUB_ID_NUMBER AND GIFT_CLUB_STATUS = 'A' AND GIFT_CLUB_CODE = 'NUL'

----- RATINGS
LEFT OUTER JOIN EVALUATION EV ON E.ID_NUMBER = EV.ID_NUMBER
LEFT OUTER JOIN TMS_RATING RATING ON EV.RATING_CODE = RATING.rating_code

GROUP BY
E.ID_NUMBER,
E.PREF_MAIL_NAME,
E.LAST_NAME,
E.FIRST_NAME,
RATING.SHORT_DESC,
QUALIFICATION_DESC,
E.INSTITUTIONAL_SUFFIX,
P.PROSPECT_ID,
MGR.REPORT_NAME,
P.ACTIVE_IND,
STAGE.short_desc,
LIFETIME_NEWGIFT_CMIT,
AFFINITY_SCORE,

ADR.STREET1,
ADR.STREET2,
ADR.STREET3,
ADR.CITY,
ADR.STATE_CODE,
ADR.ZIPCODE,
ADR.COUNTRY_CODE,

E.BIRTH_DT,

MGR_SPS.REPORT_NAME,
POTENTIAL_INTEREST_AREAS,
MULTI_OR_SINGLE_INTEREST,
D.ID_NUMBER,
D1.DEGREE_YEAR,
D1."Degree Code Desc",
D1."Degree Level Desc",
D1."Department Desc",
D1."Concentration Desc",

D2.DEGREE_YEAR,
D2."Degree Code Desc",
D2."Degree Level Desc",
D2."Department Desc",
D2."Concentration Desc",

D3.DEGREE_YEAR,
D3."Degree Code Desc",
D3."Degree Level Desc",
D3."Department Desc",
D3."Concentration Desc",
CASE WHEN D1."Financial Aid Desc" LIKE '%RECEIVED%' OR D2."Financial Aid Desc" LIKE '%RECEIVED%' OR D3."Financial Aid Desc" LIKE '%RECEIVED%' THEN 'Y' ELSE NULL END,
  
EVT.EVENT_START_DATETIME,
EVT.EVENT_NAME,
EVT.Event_Type,

CT.CONTACT_DATE,
CT.CONTACT_TYPE_DESC,
CT.DESCRIPTION,
CT.CONTACT_PURPOSE_DESC,
CT.CONTACTER,

F."Entity Name",

G.DATE_OF_RECORD,
G.CREDIT_AMOUNT,
G.ALLOCATION_CODE || ' - ' || G.ALLOC_SHORT_NAME || ' - ' || G."Allocation School",

E.ID_NUMBER,
E.SPOUSE_ID_NUMBER,

GC.GIFT_CLUB_REASON;
