CREATE OR REPLACE VIEW RPT_RVA7647.FSM_NOTES AS

SELECT
N.ID_NUMBER AS "ID Number",
N.NOTE_DATE AS "Note Date",
CASE WHEN EXTRACT(MONTH FROM N.NOTE_DATE) >= 9
THEN EXTRACT(YEAR FROM N.NOTE_DATE)+1
ELSE EXTRACT(YEAR FROM N.NOTE_DATE)
END AS "Fiscal Year",
N.NOTE_TYPE AS "Note Type Code",
TMS_nTYPE.short_desc AS "Note Type Desc",
N.AUTHOR_ID_NUMBER AS "Author ID Number",
e.report_name As "Contacter",
N.DESCRIPTION AS "Note Title",
N.BRIEF_NOTE AS "Note Description",
ROW_NUMBER() OVER (PARTITION BY N.ID_NUMBER ORDER BY N.NOTE_DATE DESC) AS Rw
FROM NOTES N
INNER JOIN FSM_DAR_STAFF ON N.AUTHOR_ID_NUMBER = FSM_DAR_STAFF.ID_NUMBER
INNER JOIN ENTITY E ON N.AUTHOR_ID_NUMBER = E.ID_NUMBER
Inner Join tms_note_type tms_ntype On tms_ntype.note_type = n.note_type
;
