CREATE OR REPLACE VIEW RPT_RVA7647.FSM_PHONES AS

SELECT DISTINCT
T.ID_NUMBER AS "ID Number",
CASE 
  WHEN T.AREA_CODE IS NULL OR T.AREA_CODE IN ('',' ') THEN SUBSTR(T.TELEPHONE_NUMBER,1,3) || '-' || SUBSTR(T.TELEPHONE_NUMBER,4,4)
  WHEN LENGTH(TELEPHONE_NUMBER) > 7 THEN TELEPHONE_NUMBER
    ELSE '(' || T.AREA_CODE || ') ' || SUBSTR(T.TELEPHONE_NUMBER,1,3) || '-' || SUBSTR(T.TELEPHONE_NUMBER,4,4) END AS "Phone",
T.TELEPHONE_TYPE_CODE AS "Phone Type Code",
TT.SHORT_DESC AS "Phone Type Desc",
T.TELEPHONE_STATUS_CODE AS "Phone Status Code",
PS.SHORT_DESC AS "Phone Status Desc",
T.PREFERRED_IND AS "Preferred",
T.START_DT AS "Start Date",
ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY CASE WHEN T.PREFERRED_IND = 'Y' THEN 1 WHEN PS.hierarchy_order = 0 THEN 1000 ELSE PS.hierarchy_order END) AS Rw
FROM TELEPHONE T
LEFT OUTER JOIN ADVANCE.TMS_TELEPHONE_TYPE TT ON T.TELEPHONE_TYPE_CODE = TT.TELEPHONE_TYPE_CODE
LEFT OUTER JOIN ADVANCE.TMS_PHONE_STATUS PS ON T.TELEPHONE_STATUS_CODE = PS.PHONE_STATUS_CODE
WHERE
TELEPHONE_STATUS_CODE = 'A'
;
