--------CURRENT FISCAL YEAR FACULTY GIVING REPORT--------
-----ANDREW GUTIERREZ (andrew.gutierrez@northwestern.edu------

WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT
E.ID_NUMBER,
E.PREF_MAIL_NAME AS "Preferred Mail Name",
G.TRANS_ID_NUMBER AS "Transaction ID",
CASE WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC ELSE T.TRANSACTION_TYPE_DESC END AS "Type of Transaction",
G.YEAR_OF_GIVING AS "Fiscal Year",
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Date(mmddyyyy)", 
G.NEW_GIFTS_AND_CMIT_AMT AS "New Gifts and Commitments",
CAST(G.MATCHING_GIFT_CREDIT_AMOUNT + G.PLEDGE_CREDIT_DISC_AMOUNT + CASE WHEN TG.TRANSACTION_GROUP_CODE = 'G' THEN G.GIFT_CREDIT_AMOUNT ELSE 0.00 END AS FLOAT) AS "NGC Soft Credit Amount",
--GA.GIFT_ASSOCIATED_DESC AS "Gift Association",
AL.ALLOC_SHORT_NAME AS "Allocation Short Name",
RA.REPORTING_AREA_FULL_DESC AS "Reporting Area Long Name",
A.APPEAL_CODE AS "Appeal Code"
FROM FACULTY_IDS F
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G ON F.ID_NUMBER = G.ENTITY_ID_NUMBER
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON F.ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_REPORTING_AREA@catrackstobi RA ON G.REPORTING_AREA_SID = RA.REPORTING_AREA_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID 
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
--LEFT OUTER JOIN DM_ARD.DIM_GIFT_ASSOCIATION@catrackstobi GA ON G.GIFT_ASSOCIATED_SID = GA.GIFT_ASSOCIATED_SID
WHERE
YEAR_OF_GIVING IN ('2024')
AND
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
G.APPEAL_SID NOT IN (17710,17711,12471) ----- EXCLUDE AFFIL, HOSPF, CLINT, BLANK APPEALS

ORDER BY
G.NEW_GIFTS_AND_CMIT_AMT DESC
