SELECT
A.FSM_ID,
A.ID_NUMBER,
A.N_APPEAL_CODE,
A.APPEAL_YEAR,
A.APPEAL_MONTH,
AP.*,
G.*
FROM FSM_GP_APPEAL_DATA A
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON AP.APPEAL_CODE = A.N_APPEAL_CODE
INNER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G ON G.APPEAL_SID = AP.APPEAL_SID
