WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT
E.ID_NUMBER AS "ID Number",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
E.CITY AS "City",
E.STATE_CODE AS "State",
P.PROSPECT_MANAGER_NAME AS "Manager",
CASE WHEN DD.FSM_DEGREE_FLAG = 'Y' THEN 'Y' ELSE 'N' END AS "Feinberg Alum",
CASE WHEN E.ID_NUMBER IN (SELECT DISTINCT ENTITY_KEY FROM DM_ARD.DIM_AFFILIATION_DETAIL@catrackstobi WHERE AFFIL_LEVEL_CODE = 'CC') THEN 'Y' ELSE 'N' END AS "Clinic Client",
--DS.LIFETIME_GIFT_CREDIT_AMOUNT AS "NU Lifetime Giving",
DS2.LIFETIME_GIFT_CREDIT_AMOUNT AS "FSM Lifetime Giving",
E.PR_RATING_DESC AS "Wealth Rating",
E.AFFINITY_SCORE AS "Affinity Score",
CASE WHEN G3.ENTITY_ID_NUMBER IS NOT NULL THEN 'Reactivated' ELSE 'New' END AS "FSM Donor Type",
MAX(TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD')) AS "Prior Most Recent Gift Date",

G.TRANS_ID_NUMBER AS "Transaction ID",
G.YEAR_OF_GIVING AS "Fiscal Year",
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Gift Date", 
G.NEW_GIFTS_AND_CMIT_AMT AS "Gift Amount",
CASE WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC ELSE T.TRANSACTION_TYPE_DESC END AS "Type of Transaction",
A.APPEAL_CODE AS "Appeal Code",
A.DESCRIPTION AS "Appeal Description",
A.APPEAL_GROUP_DESC AS "Appeal Group",
A.APPEAL_TYPE_DESC AS "Appeal Type",
AL.ALLOCATION_CODE AS "Allocation Code",
AL.ALLOC_SHORT_NAME AS "Allocation Short Name",
RA.REPORTING_AREA_FULL_DESC AS "Reporting Area Long Name"
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID AND A.PARENT_UNIT_CODE = 'FS' 
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON G.ENTITY_ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_REPORTING_AREA@catrackstobi RA ON G.REPORTING_AREA_SID = RA.REPORTING_AREA_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID 
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.ENTITY_ID_NUMBER = G2.ENTITY_ID_NUMBER AND G2.REPORTING_AREA_SID = '21' AND TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AND MONTHS_BETWEEN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD'),TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD')) <= 60
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G3 ON G.ENTITY_ID_NUMBER = G3.ENTITY_ID_NUMBER AND G3.REPORTING_AREA_SID = '21' AND TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AND MONTHS_BETWEEN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD'),TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD')) > 60
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi DS ON E.ID_NUMBER = DS.ENTITY_KEY AND DS.REPORTING_AREA = 'NA' AND DS.ANNUAL_FUND_FLAG = 'N' -- ALL NU LIFETIME GIVING
LEFT OUTER JOIN DM_ARD.FACT_DONOR_SUMMARY@catrackstobi DS2 ON E.ID_NUMBER = DS2.ENTITY_KEY AND DS2.REPORTING_AREA = 'FS' AND DS2.ANNUAL_FUND_FLAG = 'N' -- FEINBERG LIFETIME GIVING
LEFT OUTER JOIN DM_ARD.DIM_DEGREE_SUMMARY@catrackstobi DD ON E.ID_NUMBER = DD.ENTITY_KEY
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT_ENTITY@catrackstobi PE ON E.ID_NUMBER = PE.ID_NUMBER AND PE.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_PROSPECT@catrackstobi P ON PE.PROSPECT_ID = P.PROSPECT_ID AND P.CURRENT_INDICATOR = 'Y'
WHERE
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
G.APPEAL_SID NOT IN (17710,17711) ----- EXCLUDE AFFIL, HOSPF
AND
G.NEW_GIFTS_AND_CMIT_AMT > 0 ----- NEW COMMITMENTS ONLY
AND
G2.ENTITY_ID_NUMBER IS NULL ----- NO GIFTS IN LAST 5 YEARS
AND
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') BETWEEN add_months(trunc(sysdate,'mm'),-1) and last_day(add_months(trunc(sysdate,'mm'),-1)) ----- GIFTS FROM THE PREVIOUS MONTH
AND
(DD.FSM_DEGREE_FLAG <> 'Y' ----- NON-FEINBERG ALUM
OR
(DD.FSM_DEGREE_FLAG = 'Y' AND E.ID_NUMBER IN (SELECT DISTINCT ENTITY_KEY FROM DM_ARD.DIM_AFFILIATION_DETAIL@catrackstobi WHERE AFFIL_LEVEL_CODE = 'CC')) ----- FEINBERG ALUM AND CONFIRMED PATIENT
)
AND
COALESCE(AL.ALLOC_DEPT_DESC,' ') NOT IN ('Medical School FA') ----- FILTER OUT ALUMNI FUNDS
AND
COALESCE(A.APPEAL_GROUP_DESC,' ') NOT IN ('FSM Alumni Giving') ----- FILTER OUT ALUMNI APPEALS
AND
E.PERSON_OR_ORG = 'P' ----- ONLY INDIVIDUALS

GROUP BY
E.ID_NUMBER,
E.PREF_MAIL_NAME,
E.CITY,
E.STATE_CODE,
P.PROSPECT_MANAGER_NAME,
CASE WHEN DD.FSM_DEGREE_FLAG = 'Y' THEN 'Y' ELSE 'N' END,
CASE WHEN E.ID_NUMBER IN (SELECT DISTINCT ENTITY_KEY FROM DM_ARD.DIM_AFFILIATION_DETAIL@catrackstobi WHERE AFFIL_LEVEL_CODE = 'CC') THEN 'Y' ELSE 'N' END,
DS2.LIFETIME_GIFT_CREDIT_AMOUNT,
CASE WHEN G3.ENTITY_ID_NUMBER IS NOT NULL THEN 'Reactivated' ELSE 'New' END,
E.PR_RATING_DESC,
E.AFFINITY_SCORE,
G.TRANS_ID_NUMBER,
G.YEAR_OF_GIVING,
G.DATE_OF_RECORD_KEY,
G.NEW_GIFTS_AND_CMIT_AMT,
CASE WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC ELSE T.TRANSACTION_TYPE_DESC END,
A.APPEAL_CODE,
A.DESCRIPTION,
A.APPEAL_GROUP_DESC,
A.APPEAL_TYPE_DESC,
AL.ALLOCATION_CODE,
AL.ALLOC_SHORT_NAME,
RA.REPORTING_AREA_FULL_DESC

ORDER BY
G.DATE_OF_RECORD_KEY DESC,
G.NEW_GIFTS_AND_CMIT_AMT DESC
