CREATE OR REPLACE VIEW RPT_RVA7647.FSM_GP_AG_STATS AS

WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
),

APP_COUNTS AS (
SELECT
A.N_APPEAL_CODE,
COUNT(DISTINCT CASE WHEN FSM_ID IS NOT NULL THEN FSM_ID ELSE A.ID_NUMBER END) AS "Number of Recipients"
FROM FSM_GP_APPEAL_DATA A
GROUP BY
A.N_APPEAL_CODE
),

SUMS AS (
SELECT
AP.APPEAL_CODE AS "Appeal Code",
AP.DESCRIPTION AS "Appeal Description",
G.APPEAL_SID,
AP.DATE_ADDED AS "Appeal Date",
G.YEAR_OF_GIVING AS "Fiscal Year",
A."Number of Recipients",
COUNT(DISTINCT G.TRANS_ID_NUMBER) AS "Number of Gifts",
COUNT(DISTINCT G.ENTITY_ID_NUMBER) AS "Number of Donors",
SUM(G.NEW_GIFTS_AND_CMIT_AMT) AS "Amount Raised",
LTRIM(TO_CHAR(AVG(G.NEW_GIFTS_AND_CMIT_AMT),'99999999.99')) AS "Average Gift Amount"

FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
--INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON G.APPEAL_SID = AP.APPEAL_SID
INNER JOIN APP_COUNTS A ON AP.APPEAL_CODE = A.N_APPEAL_CODE

WHERE
G.NEW_GIFTS_AND_CMIT_AMT > 0

GROUP BY
G.APPEAL_SID,
AP.APPEAL_CODE,
AP.DESCRIPTION,
AP.DATE_ADDED,
A."Number of Recipients",
G.YEAR_OF_GIVING
),

GIFTS AS (
SELECT DISTINCT
AP.APPEAL_CODE AS "Appeal Code",
AP.DESCRIPTION AS "Appeal Description",
G.APPEAL_SID,
G.ENTITY_ID_NUMBER,
G.TRANS_ID_NUMBER,
G.DATE_OF_RECORD_KEY
FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
INNER JOIN DM_ARD.DIM_APPEAL@catrackstobi AP ON G.APPEAL_SID = AP.APPEAL_SID
INNER JOIN APP_COUNTS A ON AP.APPEAL_CODE = A.N_APPEAL_CODE

WHERE
G.NEW_GIFTS_AND_CMIT_AMT > 0
),

FTD AS (
SELECT
G."Appeal Code",
G."Appeal Description",
G.APPEAL_SID,
COUNT(DISTINCT G.ENTITY_ID_NUMBER) AS "Number of New Donors"
FROM GIFTS G
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.ENTITY_ID_NUMBER = G2.ENTITY_ID_NUMBER 
     AND G2.NEW_GIFTS_AND_CMIT_AMT > 0 AND G2.REPORTING_AREA_SID = '21' AND TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')

WHERE
G2.ENTITY_ID_NUMBER IS NULL

GROUP BY
G."Appeal Code",
G."Appeal Description",
G.APPEAL_SID
),

RD AS (
SELECT
G."Appeal Code",
G."Appeal Description",
G.APPEAL_SID,
COUNT(DISTINCT G.ENTITY_ID_NUMBER) AS "Number of Reactivated Donors"
FROM GIFTS G
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G2 ON G.ENTITY_ID_NUMBER = G2.ENTITY_ID_NUMBER 
     AND G2.NEW_GIFTS_AND_CMIT_AMT > 0 AND G2.REPORTING_AREA_SID = '21' 
     AND TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')
     AND MONTHS_BETWEEN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD'),TO_DATE(G2.DATE_OF_RECORD_KEY,'YYYYMMDD')) <= 60
LEFT OUTER JOIN DM_ARD.FACT_GIVING_TRANS@catrackstobi G3 ON G.ENTITY_ID_NUMBER = G3.ENTITY_ID_NUMBER 
     AND G3.NEW_GIFTS_AND_CMIT_AMT > 0 AND G3.REPORTING_AREA_SID = '21' 
     AND TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD') < TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD')
     AND MONTHS_BETWEEN(TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD'),TO_DATE(G3.DATE_OF_RECORD_KEY,'YYYYMMDD')) > 60
     AND G2.ENTITY_ID_NUMBER IS NULL
WHERE
G3.ENTITY_ID_NUMBER IS NOT NULL

GROUP BY
G."Appeal Code",
G."Appeal Description",
G.APPEAL_SID
)


SELECT DISTINCT
S."Appeal Code",
S."Appeal Description",
S."Appeal Date",
S."Fiscal Year",
S."Number of Recipients",
S."Number of Gifts",
S."Number of Donors",
S."Number of Donors" / S."Number of Recipients" AS "Response Rate",
NVL(FTD."Number of New Donors",0) AS "Number of New Donors",
NVL(RD."Number of Reactivated Donors",0) AS "Number of Reactivated Donors",
S."Amount Raised",
S."Average Gift Amount"

FROM SUMS S
LEFT OUTER JOIN FTD ON S."Appeal Code" = FTD."Appeal Code"
LEFT OUTER JOIN RD ON S."Appeal Code" = RD."Appeal Code"

;
