WITH CURRENT_FY AS
(SELECT CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 9
THEN EXTRACT(YEAR FROM SYSDATE)+1
ELSE EXTRACT(YEAR FROM SYSDATE)
END CFY
FROM DUAL
)

SELECT
G.ENTITY_ID_NUMBER,
TO_DATE(G.DATE_OF_RECORD_KEY,'YYYYMMDD') AS "Date(mmddyyyy)",
E.PREF_MAIL_NAME AS "Preferred Mail Name",
G.NEW_GIFTS_AND_CMIT_AMT AS "New Gifts and Commitments",
CASE WHEN G.TRANSACTION_GROUP_SID = 10 AND G.TRANSACTION_TYPE_SID = 0 THEN TG.TRANSACTION_SUB_GROUP_DESC WHEN G.PRIMARY_PLEDGE_SID > 0 AND G.TRANSACTION_TYPE_SID = 0 THEN PP.PLEDGE_TYPE_DESC ELSE T.TRANSACTION_TYPE_DESC END AS "Type of Transaction",
CASE WHEN DAR.LAST_NAME IS NOT NULL THEN P.PROPOSAL_TITLE ELSE AL.LONG_NAME END AS "Gift Reason",
CASE WHEN DAR.LAST_NAME IS NOT NULL THEN CONCAT(CONCAT(' (', + DAR.LAST_NAME), ')') ELSE ' ' END AS "Proposal Manager"

FROM DM_ARD.FACT_GIVING_TRANS@catrackstobi G
INNER JOIN CURRENT_FY ON G.YEAR_OF_GIVING = CURRENT_FY.CFY
LEFT OUTER JOIN DM_ARD.DIM_ENTITY@catrackstobi E ON G.ENTITY_ID_NUMBER = E.ID_NUMBER AND E.CURRENT_INDICATOR = 'Y'
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_TYPE@catrackstobi T ON G.TRANSACTION_TYPE_SID = T.TRANSACTION_TYPE_SID
LEFT OUTER JOIN DM_ARD.DIM_APPEAL@catrackstobi A ON G.APPEAL_SID = A.APPEAL_SID
LEFT OUTER JOIN DM_ARD.DIM_ALLOCATION@catrackstobi AL ON G.ALLOCATION_SID = AL.ALLOCATION_SID
LEFT OUTER JOIN DM_ARD.DIM_REPORTING_AREA@catrackstobi RA ON G.REPORTING_AREA_SID = RA.REPORTING_AREA_SID
LEFT OUTER JOIN DM_ARD.DIM_PRIMARY_PLEDGE@catrackstobi PP ON G.PRIMARY_PLEDGE_SID = PP.PRIMARY_PLEDGE_SID 
LEFT OUTER JOIN DM_ARD.DIM_TRANSACTION_GROUP@catrackstobi TG ON G.TRANSACTION_GROUP_SID = TG.TRANSACTION_GROUP_SID
LEFT OUTER JOIN DM_ARD.DIM_PROPOSAL@catrackstobi P ON G.PROPOSAL_ID = P.PROPOSAL_ID AND P.CURRENT_INDICATOR = 'Y' AND P.DELETED_FLAG = 'N'
LEFT OUTER JOIN RPT_RVA7647.FSM_DAR_STAFF DAR ON P.PROPOSAL_MANAGER_ID_NUMBER = DAR.ID_NUMBER

WHERE
G.REPORTING_AREA_SID = '21' ---- FEINBERG
AND
G.APPEAL_SID NOT IN (17710,17711) ----- EXCLUDE AFFIL, HOSPF, BLANK APPEALS
AND
G.NEW_GIFTS_AND_CMIT_AMT >= 100000
AND
G.DATE_OF_RECORD_KEY >= '20231108'

ORDER BY
G.NEW_GIFTS_AND_CMIT_AMT DESC
